marigold-ui/marigold

- .eslintignore
- .eslintrc
> chore(setup): eslint

- .vscode/extensions.json
> chore(setup): Setup vs code

- .all-contributorsrc
- README.md
- package.json
- yarn.lock
> chore(setup): all-contributors

- .all-contributorsrc
> chore(setup): update all-contributors

- README.md
> chore(setup): update readme all-contributors

- .dependabot/config.yml
> chore(setup): add dependabot for weekly updates

- .circleci/config.yml
> chore(setup): circle ci

- .gitignore
- package.json
- packages/components/package.json
- packages/system/package.json
- yarn.lock
> chore(setup): building

- README.md
> chore(update): Readme.md

- .storybook/main.js
- package.json
reason: stopped working /shrug
> chore: remove storybook ts preset

- .circleci/config.yml
- package.json
> chore(setup): add type checking

- packages/system/src/MarigoldProvider.test.tsx
- packages/system/src/MarigoldProvider.tsx
> chore(setup): MarigoldProvider

- README.md
> docs: add basic info

- packages/components/src/reservixB2BTheme.ts
- packages/components/src/theme.ts
> feat: Reservix B2B Theme

- packages/system/src/Box/Box.stories.mdx
- packages/system/src/Box/Box.test.tsx
- packages/system/src/Box/Box.tsx
- packages/system/src/Box/index.ts
> chore: box documentation

- packages/system/src/writeComponent.stories.mdx
> docs: how to write components

- jest.config.js
> chore: ignore themes/ in coverage

- packages/components/package.json
- packages/components/src/TestComponent/Checkbox.stories.mdx
- packages/components/src/Text/Text.stories.mdx
- packages/components/src/Text/Text.test.tsx
- packages/components/src/Text/Text.tsx
- packages/system/src/index.ts
- yarn.lock
> chore: implement text component

- .circleci/config.yml
> fix: run deploy storybook in CircleCI

- .eslintignore
- package.json
- yarn.lock
closes #138 
idk which dependencies (where) to drop?
> chore(setup): use tsdx (#138)

- packages/components/src/Button/Button.stories.mdx
- packages/components/src/Button/Button.test.tsx
- packages/components/src/Button/Button.tsx
- packages/components/src/Button/index.ts
> feat: implement <Button/> component

- packages/components/src/Button/Button.stories.mdx
- themes/theme-b2b/src/index.ts
- themes/theme-unicorn/src/index.ts
> chore: update button theming

- packages/components/src/Button/Button.stories.mdx
- packages/components/src/index.ts
- packages/system/src/Box/Box.stories.mdx
closes #117 
> Theme styling are included if #184 is merged!
> chore(doc): add example to <Box/> doc

- packages/system/src/Box/Box.stories.mdx
small fix to show custom css style in box doc button example
> chore: make better box doc example

- config/eslint/index.js
- config/eslint/package.json
- package.json
- yarn.lock
> chore: Add "eslint-plugin-testing-library"

- jest.config.js
- packages/system/src/MarigoldProvider.test.tsx
- packages/system/src/MarigoldProvider.tsx
> feat: Support "reduce-motion" media query

- package.json
> fix: remove clean:build from release script (#107)

- .circleci/config.yml
- .github/workflows/validate.yml
> chore: move lint, typecheck and test to GH Actions (#109)

- .github/labeler.yml
- .github/workflows/labeler.yml
- .github/workflows/stale.yml
> chore: add labeler and stale workflows (#109)

- config/storybook/preview.js
> chore: set b2b as default theme

- .github/labeler.yml
> fix: adjust paths for labeler

- packages/components/src/Svg/Svg.test.tsx
> test: svg component test

- packages/icons/src/index.ts
> bugfix: storybook error because of missing index.ts in icons

- packages/components/src/Button/Button.tsx
> fix: order of Button css prop

- packages/components/src/Text/Text.stories.mdx
- packages/components/src/Text/Text.test.tsx
- packages/components/src/Text/Text.tsx
- themes/theme-b2b/src/index.ts
- removed headings and variant
- adjusted tests, description, property tables and examples
- added correct margin styles for `p` element
> feat: update text component

- .github/workflows/stale.yml
> fix: correct repo token in stale workflow

- scripts/create.ts
> feat: add new component to exports in component package

- config/eslint/package.json
- package.json
> fix: move react-app to root

- packages/components/src/Button/Button.stories.mdx
- packages/components/src/Button/Button.test.tsx
- packages/components/src/Button/Button.tsx
- packages/components/src/Svg/Svg.tsx
- themes/theme-b2b/src/index.ts
> feat: align icon in button

- packages/system/src/concepts-principles.mdx
- Design tokens
- Harmony and Rhythm
Ref #144
> feat(docs): First part of "concepts & principles"

- packages/components/src/Label/Label.test.tsx
> fix: correct label test

- themes/theme-b2b/src/index.ts
> fix: make label as wide as it needs to be and not wider

- packages/components/src/Select/Select.stories.mdx
- packages/components/src/Select/Select.test.tsx
- packages/components/src/Select/Select.tsx
- packages/components/src/Select/index.ts
- packages/components/src/index.ts
- themes/theme-b2b/src/index.ts
> feat: add dropdown component

- packages/components/src/Checkbox/Checkbox.stories.mdx
- packages/components/src/Checkbox/Checkbox.test.tsx
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/Checkbox/index.ts
- packages/components/src/index.ts
> feat: add checkbox component

- packages/components/src/Checkbox/Checkbox.stories.mdx
- packages/components/src/Checkbox/Checkbox.tsx
- themes/theme-b2b/src/index.ts
> feat: finish checkbox component

- packages/components/src/Button/Button.stories.mdx
- packages/components/src/Checkbox/Checkbox.stories.mdx
- packages/components/src/Heading/Heading.stories.mdx
- packages/components/src/Label/Label.stories.mdx
- packages/components/src/Radio/Radio.stories.mdx
- packages/components/src/Select/Select.stories.mdx
- packages/components/src/Slider/Slider.stories.mdx
- packages/components/src/Svg/Svg.stories.mdx
- packages/components/src/Text/Text.stories.mdx
- packages/components/src/TextInput/TextInput.stories.mdx
- packages/components/src/Textarea/Textarea.stories.mdx
I thought this would be a good idea.
But one thing we have to discuss. Viktorias "create component" script can't handle this structure.
If we merge this PR we have to write the kind of component by ourselves.
What do you think? @viktoria-schwarz @sebald
> refa: sort components in storybook

- package.json
- packages/components/src/Text/Text.stories.mdx
- themes/theme-b2b/src/index.ts
> change Text color

- packages/components/src/Divider/Divider.stories.mdx
- packages/components/src/Divider/Divider.test.tsx
- packages/components/src/Divider/Divider.tsx
- packages/components/src/Divider/index.ts
- packages/components/src/index.ts
- themes/theme-b2b/src/index.ts
> feat: add Divider component

- packages/components/src/Container/Container.stories.mdx
- packages/components/src/Container/Container.test.tsx
- packages/components/src/Container/Container.tsx
- packages/components/src/Container/index.ts
- packages/components/src/index.ts
- themes/theme-b2b/src/index.ts
> feat: add container component

- packages/components/src/Text/Text.stories.mdx
- packages/components/src/Text/Text.test.tsx
- packages/components/src/Text/Text.tsx
> feat: add textColor prop

- config/storybook/package.json
- yarn.lock
Reverts marigold-ui/marigold#459
> Revert "chore(deps): bump @storybook/react from 6.0.16 to 6.0.20"

- packages/components/src/Input/Input.stories.mdx
- packages/components/src/Input/Input.test.tsx
- packages/components/src/Input/Input.tsx
- packages/components/src/Input/index.ts
- packages/components/src/TextInput/index.ts
- packages/components/src/index.ts
> rename TextInput to Input

- config/eslint/package.json
- config/jest/package.json
- config/storybook/package.json
- package.json
- packages/components/package.json
- packages/components/src/Checkbox/Checkbox.test.tsx
- packages/layout/package.json
- themes/theme-b2b/package.json
- themes/theme-unicorn/package.json
- yarn.lock
solves versioning problems we had with Storybook 6
> updates of all package.jsons after storybook upgrade to 6

- packages/components/src/Alert/Alert.stories.mdx
- packages/components/src/Alert/Alert.test.tsx
- packages/components/src/Alert/Alert.tsx
> rewrite Alert

- packages/components/src/Container/Container.stories.mdx
- packages/components/src/Container/Container.test.tsx
- packages/components/src/Container/Container.tsx
- themes/theme-b2b/src/index.ts
- themes/theme-unicorn/src/index.ts
> rewrite Container

- packages/components/src/Slider/Slider.stories.mdx
- packages/components/src/Slider/Slider.test.tsx
- packages/components/src/Slider/Slider.tsx
- packages/components/src/Textarea/Textarea.stories.mdx
- packages/components/src/Textarea/Textarea.test.tsx
- packages/components/src/Textarea/Textarea.tsx
> Rewrite Slider and Textarea

- packages/components/src/Input/Input.stories.mdx
- packages/components/src/Input/Input.test.tsx
- packages/components/src/Input/Input.tsx
- packages/components/src/Label/Label.stories.mdx
- packages/components/src/Label/Label.test.tsx
- packages/components/src/Label/Label.tsx
> Rewrite Label and Input

- packages/components/src/Heading/Heading.stories.mdx
- packages/components/src/Heading/Heading.test.tsx
- packages/components/src/Heading/Heading.tsx
- packages/components/src/Link/Link.stories.mdx
- packages/components/src/Link/Link.test.tsx
- packages/components/src/Link/Link.tsx
> Rewrite Heading and Link

- packages/components/src/ValidationMessage/ValidationMessage.stories.mdx
- packages/components/src/ValidationMessage/ValidationMessage.test.tsx
- packages/components/src/ValidationMessage/ValidationMessage.tsx
> rewrite ValidationMessage

- packages/components/src/Checkbox/Checkbox.stories.mdx
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/Radio/Radio.stories.mdx
- packages/components/src/Radio/Radio.tsx
> Rewrite Radio and Checkbox

- packages/components/src/Button/Button.stories.mdx
- packages/components/src/Button/Button.test.tsx
- packages/components/src/Button/Button.tsx
> Rewrite Button

- packages/components/src/Field/Field.stories.mdx
- packages/components/src/Field/Field.test.tsx
- packages/components/src/Field/Field.tsx
- packages/components/src/Field/index.ts
- packages/components/src/index.ts
- themes/theme-b2b/src/index.ts
> feat: add field component

- .github/dependabot.yml
- .kodiak.toml
> chore: add auto approve review

- packages/components/src/Alert/Alert.stories.mdx
- packages/components/src/Alert/Alert.test.tsx
- packages/components/src/Alert/Alert.tsx
- packages/components/src/Badge/Badge.test.tsx
- packages/components/src/Badge/Badge.tsx
- packages/components/src/Text/Text.tsx
- packages/system/src/useStyles.test.tsx
- packages/system/src/useStyles.ts
> change useStyles hook to concat custom classNames and edit Text, Alert and Badge component

- packages/components/src/Menu/Menu.stories.mdx
- packages/components/src/Menu/Menu.test.tsx
- packages/components/src/Menu/Menu.tsx
- packages/components/src/Menu/index.ts
- packages/components/src/MenuItem/MenuItem.stories.mdx
- packages/components/src/MenuItem/MenuItem.test.tsx
- packages/components/src/MenuItem/MenuItem.tsx
- packages/components/src/MenuItem/index.ts
- packages/components/src/index.ts
- themes/theme-b2b/src/index.ts
> add MenuItem and Menu component

- .github/workflows/stale.yml
We are not that fast and 30 days is kinda annoying :D
> chore: Increase time before issues goes stale

- packages/components/src/Checkbox/Checkbox.stories.mdx
- packages/components/src/Checkbox/Checkbox.test.tsx
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/Radio/Radio.stories.mdx
- packages/components/src/Radio/Radio.test.tsx
- packages/components/src/Radio/Radio.tsx
> add Label to Checkbox and Radio

- packages/components/src/Message/Message.stories.mdx
- packages/components/src/Message/Message.test.tsx
- packages/components/src/Message/Message.tsx
- themes/theme-b2b/src/index.ts
- themes/theme-unicorn/src/colors.ts
- themes/theme-unicorn/src/index.ts
> Desgin update: message

- packages/components/src/Column/Column.stories.mdx
- packages/components/src/Column/Column.test.tsx
- packages/components/src/Column/Column.tsx
- packages/components/src/Column/index.ts
- packages/components/src/index.ts
> add Column Component

- packages/system/src/normalize.ts
> bug: remove circular dependency

- package.json
- packages/system/package.json
- packages/system/src/useClassname.ts
- yarn.lock
Reverts marigold-ui/marigold#737
> Revert "chore: Update to emotion 11, switch to @emotion/css"

- packages/components/src/Box/Box.tsx
- packages/components/src/Message/Message.tsx
- packages/system/src/useStyles.test.tsx
- packages/system/src/useStyles.ts
- packages/system/src/writeComponent.stories.mdx
> bug: Make element a single elementtype and adjust tests

- .github/dependabot.yml
I think this is more than enough. Daily is annoying AF
> chore: Run dependabot weekly

- packages/components/src/Box/Box.test.tsx
- packages/components/src/Box/Box.tsx
> feat(components): Let <Box> support variant prop

- packages/components/package.json
- packages/icons/package.json
- packages/images/package.json
- packages/system/package.json
- packages/types/package.json
- themes/theme-b2b/package.json
- themes/theme-unicorn/package.json
align with npm package version 0.0.2
> chore: update all packages to version 0.0.2

- package.json
- packages/components/src/Stack/Stack.stories.mdx
- packages/components/src/Stack/Stack.test.tsx
- packages/components/src/Stack/Stack.tsx
- packages/components/src/Stack/index.ts
- packages/components/src/index.ts
- packages/system/src/types.ts
- packages/system/src/useTheme.tsx
- yarn.lock
> add Stack component

- packages/components/src/Button/Button.stories.mdx
- themes/theme-b2b/src/index.ts
> complete rx b2b Button Design

- packages/components/src/Alert/Alert.tsx
- packages/components/src/Badge/Badge.tsx
- packages/components/src/Button/Button.tsx
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/Column/Column.tsx
- packages/components/src/Container/Container.tsx
- packages/components/src/Divider/Divider.tsx
- packages/components/src/Field/Field.tsx
- packages/components/src/Heading/Heading.tsx
- packages/components/src/Hidden/Hidden.tsx
- packages/components/src/Image/Image.tsx
- packages/components/src/Input/Input.tsx
- packages/components/src/Label/Label.tsx
- packages/components/src/Link/Link.tsx
- packages/components/src/Menu/Menu.tsx
- packages/components/src/MenuItem/MenuItem.tsx
- packages/components/src/Message/Message.tsx
- packages/components/src/Radio/Radio.tsx
- packages/components/src/Select/Select.tsx
- packages/components/src/Slider/Slider.tsx
- packages/components/src/Stack/Stack.tsx
- packages/components/src/Svg/Svg.tsx
- packages/components/src/Text/Text.tsx
- packages/components/src/Textarea/Textarea.tsx
- packages/components/src/ValidationMessage/ValidationMessage.tsx
> Add type exports and remove absolute imports

- packages/components/src/Alert/Alert.stories.mdx
- packages/components/src/Alert/Alert.test.tsx
- packages/components/src/Alert/Alert.tsx
- themes/theme-b2b/src/index.ts
> refa: change Alert component & design

- .github/workflows/coveralls.yml
> chore: remove coveralls token

- packages/components/src/Field/Field.tsx
> fix(Field): Fix color access

- packages/components/src/Alert/Alert.stories.mdx
- packages/components/src/Badge/Badge.stories.mdx
- packages/components/src/Box/Box.stories.mdx
- packages/components/src/Button/Button.stories.mdx
- packages/components/src/Checkbox/Checkbox.stories.mdx
- packages/components/src/Column/Column.stories.mdx
- packages/components/src/Columns/Columns.stories.mdx
- packages/components/src/Container/Container.stories.mdx
- packages/components/src/Dialog/Dialog.stories.mdx
- packages/components/src/Divider/Divider.stories.mdx
- packages/components/src/Field/Field.stories.mdx
- packages/components/src/Heading/Heading.stories.mdx
- packages/components/src/Hidden/Hidden.stories.mdx
- packages/components/src/Image/Image.stories.mdx
- packages/components/src/Input/Input.stories.mdx
- packages/components/src/Label/Label.stories.mdx
- packages/components/src/Link/Link.stories.mdx
- packages/components/src/Menu/Menu.stories.mdx
- packages/components/src/MenuItem/MenuItem.stories.mdx
- packages/components/src/Message/Message.stories.mdx
- packages/components/src/Radio/Radio.stories.mdx
- packages/components/src/Select/Select.stories.mdx
- packages/components/src/Slider/Slider.stories.mdx
- packages/components/src/Stack/Stack.stories.mdx
- packages/components/src/Text/Text.stories.mdx
- packages/components/src/Textarea/Textarea.stories.mdx
- packages/components/src/ValidationMessage/ValidationMessage.stories.mdx
> refa(storybook): remove menu categories in storybook

- packages/components/src/theme.ts
- themes/theme-b2b/src/index.ts
- themes/theme-unicorn/src/index.ts
> fix: linting

- renovate.json
> chore: set renovate to automerge

- contributing.md
> chore(docs): add contributing file

- renovate.json
> chore(renovate): add schedule for renovate bot

- packages/components/src/Alert/Alert.tsx
- packages/components/src/Badge/Badge.test.tsx
- packages/components/src/Badge/Badge.tsx
- packages/components/src/Box/Box.tsx
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/Columns/Columns.tsx
- packages/components/src/Field/Field.test.tsx
- packages/components/src/Field/Field.tsx
- packages/components/src/Menu/Menu.tsx
- packages/components/src/MenuItem/MenuItem.tsx
- packages/components/src/Message/Message.tsx
- packages/components/src/Radio/Radio.tsx
- packages/components/src/Select/Select.tsx
- packages/components/src/Slider/Slider.tsx
- packages/components/src/Text/Text.test.tsx
- packages/components/src/Text/Text.tsx
- packages/components/src/Textarea/Textarea.tsx
- packages/components/src/ValidationMessage/ValidationMessage.tsx
- packages/icons/src/SVG/SVG.test.tsx
- packages/icons/src/SVG/SVG.tsx
- packages/server/src/createStyleTag.test.tsx
- packages/server/src/renderStatic.test.tsx
- packages/system/src/useStyles.test.tsx
- packages/system/src/useStyles.ts
> feat(system): Improve types of `useStyles`

- docs/gatsby-browser.js
- docs/src/components/CodeBlock.tsx
> docs: marigold text components to mdx

- packages/components/src/index.ts
> fix(components): Export <Box> component

- docs/src/components/CopyButton.tsx
> docs: copy button variant to ghost.small

- docs/src/components/CodeBlock.tsx
- docs/src/components/CopyButton.tsx
> docs: remove inline style + edit codeBlock text view

- docs/gatsby-browser.js
> docs: add list tags to gatsby mdx components

- config/eslint/package.json
Reverts marigold-ui/marigold#1077
> Revert "fix(deps): update dependency eslint-plugin-react to v7.24.0"

- config/eslint/package.json
Reverts marigold-ui/marigold#1076
> Revert "fix(deps): update dependency eslint-plugin-import to v2.23.4"

- config/jest/package.json
Reverts marigold-ui/marigold#1075
> Revert "fix(deps): update dependency babel-jest to v27.0.2"

- config/jest/package.json
Reverts marigold-ui/marigold#1074
> Revert "fix(deps): update jest monorepo to v27 (major)"

- config/jest/package.json
Reverts marigold-ui/marigold#1073
> Revert "fix(deps): update dependency ts-jest to v27"

- package.json
Reverts marigold-ui/marigold#1072
> Revert "chore(deps): update dependency @testing-library/react-hooks to v7"

- config/eslint/package.json
Reverts marigold-ui/marigold#1071
> Revert "fix(deps): update typescript-eslint monorepo to v4.25.0"

- config/jest/package.json
- package.json
Reverts marigold-ui/marigold#1067
> Revert "chore(deps): update dependency typescript to v4.3.2"

- docs/src/components/ShowHideButton.tsx
> docs: change showHideButton style

- docs/gatsby-browser.js
- docs/src/components/MdxComponents.tsx
> chore+docs: extract mdx comps from gatsby browser to own file

- docs/src/mdx.tsx
> bugfix: give children to inlineCode

- .changeset/rare-foxes-act.md
- docs/content/start.mdx
- docs/src/components/Navigation.tsx
- docs/src/pages/index.tsx
> feat(docs): add landing page and link in the nav

- packages/system/src/reset.ts
Ref: https://twitter.com/argyleink/status/1405881231695302659
> feat(components): Add `touchAction` to reset for button and anchors

- .changeset/quick-steaks-relax.md
- packages/components/src/Stack/Stack.tsx
- packages/system/src/get.ts
- packages/system/src/useClassname.ts
- packages/system/src/useTheme.test.tsx
- packages/system/src/useTheme.tsx
> feat(system): Expose helper to transpile style object

- .changeset/perfect-pots-pump.md
- .github/workflows/deploy.yml
- docs/index.html
> chore(deploy): add deploy script and index

- .github/workflows/deploy.yml
- docs/index.html
> chore: add author identity

- config/eslint/package.json
- config/jest/package.json
- config/prettier/package.json
- config/storybook/package.json
- config/tsconfig/package.json
- docs/package.json
- package.json
- packages/components/package.json
- packages/icons/package.json
- packages/images/package.json
- packages/server/package.json
- packages/system/package.json
- packages/types/package.json
- themes/theme-b2b/package.json
- themes/theme-unicorn/package.json
> chore: update to v0.1.0

- .changeset/violet-news-relax.md
- docs/content/components/button.mdx
- packages/components/package.json
- packages/components/src/Button/Button.stories.mdx
- packages/components/src/Button/Button.test.tsx
- packages/components/src/Button/Button.tsx
- themes/theme-b2b/src/index.ts
- themes/theme-unicorn/src/index.ts
- yarn.lock
> improve Button component with react-aria

- .changeset/grumpy-buckets-help.md
- docs/gatsby-config.js
> fix(docs): remove pathPrefix

- .github/workflows/deploy.yml
> fix(docs): add clean step to deploy process

- config/storybook/preview.js
> fix(comp): correct import of MarigoldProvider

- CNAME
> fix(deploy): remove quotation marks in CNAME

- config/eslint/package.json
- yarn.lock
Reverts marigold-ui/marigold#1252
> Revert "fix(deps): update typescript-eslint monorepo to v4.31.0"

- packages/components/src/Provider/MarigoldProvider.tsx
Reverts marigold-ui/marigold#1261
> Revert "fix: remove leaking theme-ui to other packages"

- packages/components/src/Provider/MarigoldProvider.tsx
Reverts marigold-ui/marigold#1262
> Revert "Revert "fix: remove leaking theme-ui to other packages""

- package.json
- yarn.lock
Reverts marigold-ui/marigold#1286
> Revert "chore(deps): update dependency @types/node to v14.17.17"

- .changeset/big-eggs-compare.md
- docs/content/components/select.mdx
- packages/components/src/Select/ListBox.tsx
- packages/components/src/Select/ListBoxSection.tsx
- packages/components/src/Select/Select.test.tsx
- packages/components/src/index.ts
- themes/theme-b2b/src/index.ts
- themes/theme-unicorn/src/index.ts
> feature: section to select component

- .changeset/wet-news-hope.md
- packages/icons/src/SVG/SVG.test.tsx
- packages/icons/src/SVG/SVG.tsx
> refa(comp): use Element in SVG + replace useStyles

- .changeset/giant-spies-destroy.md
- docs/content/components/card.mdx
- packages/components/src/Card/Card.stories.mdx
- packages/components/src/Card/Card.test.tsx
- packages/components/src/Card/Card.tsx
- packages/components/src/Card/index.ts
- packages/components/src/index.ts
- themes/theme-b2b/src/index.ts
- themes/theme-core/src/index.ts
- themes/theme-unicorn/src/index.ts
> feat(comp): Card component

- .changeset/moody-buckets-fly.md
- docs/src/components/CodeBlock.tsx
- docs/src/mdx.tsx
> refa(comp): replace useStyles usages in docs package

- .changeset/nasty-donuts-hear.md
- packages/components/src/Badge/Badge.test.tsx
- packages/components/src/Badge/Badge.tsx
- packages/components/src/Menu/Menu.tsx
- packages/components/src/Message/Message.tsx
- packages/components/src/ValidationMessage/ValidationMessage.test.tsx
- packages/components/src/ValidationMessage/ValidationMessage.tsx
> feat(comp): replace useStyles in Badge, Menu, Message, ValMes

- .changeset/unlucky-cars-brake.md
- packages/components/src/Field/Field.test.tsx
- packages/components/src/Select/ListBox.tsx
- packages/components/src/Select/ListBoxSection.tsx
- packages/components/src/Textarea/Textarea.tsx
> refa(comp): replace useStyles in ListBox, Textarea, Field.test

- .changeset/grumpy-points-hunt.md
- docs/content/components/button.mdx
- docs/src/components/MarigoldTheme.tsx
- docs/src/components/Preview.tsx
- docs/src/mdx.tsx
- docs/src/wrapper.tsx
> feat(docs): rename CodeBlock + create MarigoldTheme wrapper + use in button.mdx

- .changeset/tame-pillows-enjoy.md
- docs/content/components/button.mdx
- docs/src/components/CopyButton.tsx
- docs/src/components/Preview.tsx
- docs/src/components/ShowHideButton.tsx
- docs/src/theme/components.ts
- docs/src/theme/typography.ts
> feat(docs): change copy and show/hide buttons + text color

- .changeset/moody-dancers-eat.md
- packages/components/src/Card/Card.stories.mdx
- packages/components/src/Card/Card.test.tsx
- packages/components/src/Card/Card.tsx
> feat(comp): remove useStyles from Card

- .changeset/sixty-pets-suffer.md
- packages/components/src/Label/Label.tsx
> feat(comp): remove useStyles from Label

- .changeset/rare-humans-float.md
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/Radio/Radio.tsx
> feat(comp): remove useStyles from Checkbox + Radio

- .changeset/clever-swans-tie.md
- packages/system/src/Element.test.tsx
> remove useStyles from Element

- .changeset/seven-shirts-doubt.md
- packages/components/src/Columns/Columns.tsx
> feat(comp): remove useStyles from Columns

- .changeset/lovely-coats-flow.md
- packages/components/src/Slider/Slider.tsx
> feat(comp): remove useStyles from Slider

- .changeset/many-cooks-hope.md
- docs/src/theme/index.ts
- docs/src/theme/root.ts
- packages/components/src/Provider/GlobalStyles.tsx
- packages/components/src/Provider/MarigoldProvider.test.tsx
- packages/components/src/Provider/MarigoldProvider.tsx
#1395
closes #1195 
closes #1197
> feat: add GlobalStyles

- .changeset/young-mayflies-drum.md
- docs/src/theme/root.ts
> bugfix(docs): set root margin to fix ThemeSelect

- .changeset/shiny-bulldogs-lie.md
- packages/components/package.json
- packages/icons/package.json
- yarn.lock
and remove components dep from icons
> infra(packages): add icons package as dependency to component package

- .changeset/chilled-dodos-think.md
- docs/content/components/stack.mdx
- packages/components/src/Stack/Stack.stories.mdx
> refa(comp): Stack

- .changeset/empty-ants-float.md
- packages/components/src/Provider/MarigoldProvider.test.tsx
- packages/components/src/Provider/MarigoldProvider.tsx
- packages/system/src/Element.tsx
- packages/system/src/useTheme.test.tsx
- packages/system/src/useTheme.tsx
This way we can pass down theme functions in `<Element>`
> feat(system): Use emotion's context

- .changeset/twenty-donkeys-smash.md
- docs/content/components/column.mdx
- docs/content/components/columns.mdx
- docs/src/components/Layout.tsx
- packages/components/src/Column/Column.stories.mdx
- packages/components/src/Columns/Columns.stories.mdx
- packages/components/src/Columns/Columns.test.tsx
- packages/components/src/Columns/Columns.tsx
> feat(comp): improve Column + Columns component

- .changeset/light-carrots-boil.md
- docs/content/components/inline.mdx
- packages/components/src/Inline/Inline.stories.mdx
- packages/components/src/Inline/Inline.test.tsx
- packages/components/src/Inline/Inline.tsx
- packages/components/src/Inline/index.ts
- packages/components/src/index.ts
> feat(comp): inline Component

- .changeset/angry-hats-protect.md
- packages/system/src/Element.tsx
- packages/system/src/useTheme.tsx
> refa: use emotion's theme function in <Element>

- .changeset/heavy-camels-shake.md
- docs/src/components/DoAndDont.tsx
> design(docs): DoAndDont comp padding change

- packages/components/src/Box.ts
> fix: fix docs build

- .changeset/wicked-seas-own.md
- themes/theme-b2b/src/components.ts
- themes/theme-b2b/src/typography.ts
> fix(b2b-theme): set correct lineHeight for prime button

- .changeset/famous-foxes-travel.md
- docs/content/components/input.mdx
- docs/content/components/label.mdx
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/Field/Field.tsx
- packages/components/src/Label/Label.test.tsx
- packages/components/src/Label/Label.tsx
- packages/components/src/Radio/Radio.tsx
- themes/theme-b2b/src/components.ts
- themes/theme-core/src/components.ts
- themes/theme-unicorn/src/components.ts
> feat(comp): improve Label and add color prop

- .changeset/tidy-mice-return.md
- docs/content/components/field.mdx
- packages/components/src/Field/Field.stories.mdx
- packages/components/src/Field/Field.test.tsx
- packages/components/src/Field/Field.tsx
- themes/theme-b2b/src/components.ts
- themes/theme-core/src/components.ts
- themes/theme-unicorn/src/components.ts
> feat(comp): Field fix default variant + remove hardcoded variants

- .changeset/spotty-mirrors-shave.md
- docs/content/components/radio.mdx
- packages/components/src/Radio/Radio.stories.mdx
- packages/components/src/Radio/Radio.test.tsx
- packages/components/src/Radio/Radio.tsx
- themes/theme-b2b/src/components.ts
- themes/theme-core/src/components.ts
- themes/theme-unicorn/src/components.ts
> feat(comp): remove hard coded label variant in radio

- .changeset/wild-snails-live.md
- docs/content/components/checkbox.mdx
- packages/components/src/Checkbox/Checkbox.stories.mdx
- packages/components/src/Checkbox/Checkbox.test.tsx
- packages/components/src/Checkbox/Checkbox.tsx
- themes/theme-b2b/src/components.ts
- themes/theme-core/src/components.ts
- themes/theme-unicorn/src/components.ts
> feat(comp): remove hard coded label variant in checkbox

- .changeset/fresh-beds-float.md
- packages/system/src/Box.tsx
- packages/system/src/conditional.test.tsx
- packages/system/src/conditional.tsx
- packages/system/src/index.ts
> feat(system): conditional helper to allow state in variants

- .changeset/hungry-eyes-draw.md
- docs/content/components/select.mdx
- packages/components/src/Select/Select.stories.mdx
- packages/components/src/Select/Select.test.tsx
- packages/components/src/Select/Select.tsx
> feat(comp): remove hard coded label from Select

- .changeset/cuddly-lizards-yell.md
- docs/content/components/divider.mdx
- docs/src/theme/components.ts
- packages/components/package.json
- packages/components/src/Divider/Divider.stories.tsx
- packages/components/src/Divider/Divider.test.tsx
- packages/components/src/Divider/Divider.tsx
- themes/theme-b2b/src/components.ts
- themes/theme-core/src/components.ts
- themes/theme-unicorn/src/components.ts
- yarn.lock
> feat(comp): rewrite Divider and add react-aria

- packages/components/package.json
- packages/icons/package.json
- packages/system/package.json
- scripts/release.mjs
- themes/theme-b2b/package.json
- themes/theme-core/package.json
- themes/theme-unicorn/package.json
- yarn.lock
Changeset currently does not support yarn 2 :-(
See https://github.com/changesets/changesets/issues/714
> chore: fallback to yarn for publishing

- .changeset/chilly-ants-approve.md
- config/tsconfig/base.json
- config/tsconfig/package.json
- config/tsconfig/react.json
- package.json
- packages/components/package.json
- packages/components/tsconfig.build.json
- packages/components/tsup.config.json
- packages/icons/package.json
- packages/icons/tsconfig.build.json
- packages/icons/tsup.config.json
- packages/system/package.json
- packages/system/src/SVG.tsx
- packages/system/tsconfig.build.json
- packages/system/tsup.config.json
- themes/theme-b2b/package.json
- themes/theme-b2b/tsconfig.build.json
- themes/theme-b2b/tsup.config.json
- themes/theme-core/package.json
- themes/theme-core/tsconfig.build.json
- themes/theme-core/tsup.config.json
- themes/theme-unicorn/package.json
- themes/theme-unicorn/tsconfig.build.json
- themes/theme-unicorn/tsup.config.json
- tsconfig.json
- yarn.lock
> chore: Use `tsup` to build packages

- docs/content/introduction/01-about.mdx
> docs: fix typos

- .changeset/rare-seahorses-add.md
- packages/system/src/index.ts
- packages/system/src/useResponsiveValue.ssr.test.tsx
- packages/system/src/useResponsiveValue.test.tsx
- packages/system/src/useResponsiveValue.ts
> feat(system): add hook that allows to use values based on screen size

- .changeset/cyan-roses-heal.md
- docs/content/components/checkbox.mdx
- packages/components/src/Checkbox/Checkbox.stories.tsx
- packages/components/src/Checkbox/Checkbox.test.tsx
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/Checkbox/CheckboxIcon.tsx
> feat(comp): Radio remove label prop and add children + refa

- .changeset/silent-books-explode.md
- docs/src/components/CopyButton.tsx
- docs/src/components/DoAndDont.tsx
- docs/src/components/Navigation/Navigation.tsx
- docs/src/components/Navigation/useNavigation.ts
- docs/src/components/Preview.tsx
- docs/src/components/ShowHideButton.tsx
- docs/src/components/ThemeSwitch.tsx
> refa(docs): use interface instead of type

- .changeset/five-fans-lick.md
- packages/components/src/ActionGroup/ActionGroup.tsx
- packages/components/src/Alert/Alert.tsx
- packages/components/src/Badge/Badge.tsx
- packages/components/src/Button/Button.tsx
- packages/components/src/Card/Card.tsx
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/Column/Column.tsx
- packages/components/src/Columns/Columns.tsx
- packages/components/src/Container/Container.test.tsx
- packages/components/src/Container/Container.tsx
- packages/components/src/Dialog/Dialog.tsx
- packages/components/src/Divider/Divider.tsx
- packages/components/src/Image/Image.tsx
- packages/components/src/Inline/Inline.tsx
- packages/components/src/Input/Input.tsx
- packages/components/src/Link/Link.tsx
- packages/components/src/Menu/Menu.tsx
- packages/components/src/MenuItem/MenuItem.test.tsx
- packages/components/src/MenuItem/MenuItem.tsx
- packages/components/src/Message/Message.tsx
- packages/components/src/Radio/Radio.tsx
- packages/components/src/Slider/Slider.tsx
- packages/components/src/Stack/Stack.tsx
- packages/components/src/Text/Text.tsx
- packages/components/src/ValidationMessage/ValidationMessage.tsx
> refa(comp): use interface instead of type

- .vscode/extensions.json
> chore: add recommended extensions

- .changeset/poor-pianos-act.md
- scripts/release.mjs
> chore: add yarn install for locally release script

- config/storybook/package.json
- packages/components/src/Checkbox/CheckboxIcon.tsx
- packages/components/src/Dialog/ModalDialog.tsx
- packages/components/src/Label/Label.tsx
- packages/components/src/Radio/RadioIcon.tsx
- packages/system/src/Box.tsx
- packages/system/src/SVG.tsx
- packages/system/src/useTheme.tsx
- packages/system/src/variant.ts
- yarn.lock
> refa: use interface instead of type

- .changeset/poor-gifts-hug.md
- packages/components/package.json
- packages/components/src/Columns/Columns.tsx
- packages/components/src/Inline/Inline.tsx
- packages/components/src/Stack/Stack.tsx
- packages/components/src/utils/flatten-children.test.tsx
- packages/components/src/utils/flatten-children.ts
- packages/components/src/utils/index.ts
- yarn.lock
> fix(components): Use own `flattenChildren` helper to fix ESM build

- .changeset/hot-emus-compare.md
- .gitignore
- package.json
- scripts/release.mjs
- scripts/slack-release-notification.mjs
- yarn.lock
> chore: automated slack notification by new release

- .changeset/popular-jokes-confess.md
- themes/theme-core/src/components.ts
> theme(core): change button styles

- .changeset/brave-planes-turn.md
- packages/system/src/Global.test.tsx
- packages/system/src/Global.tsx
See https://css-tricks.com/your-css-reset-needs-text-size-adjust-probably/ for reasoning
> feat(system): Add textSizeAdjust to globals

- .changeset/tame-geese-compete.md
- docs/content/components/checkbox.mdx
- packages/components/src/Checkbox/Checkbox.stories.tsx
- packages/components/src/Checkbox/Checkbox.test.tsx
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/Checkbox/CheckboxIcon.tsx
> feat(comp): Checkbox add indeterminate state + doc update

- .changeset/rich-tigers-thank.md
- docs/content/components/alert.mdx
- packages/components/src/Alert/Alert.stories.tsx
- packages/components/src/Alert/Alert.tsx
- themes/theme-b2b/src/components.ts
- themes/theme-core/src/components.ts
- themes/theme-unicorn/src/components.ts
context: https://www.figma.com/file/TIRxkIDpdqb52J52PldLxl/Guidelines?node-id=60%3A552
> feat(comp/docs): Alert update variant + docs

- .vscode/settings.json
> chore: default settings in repo

- .changeset/afraid-cars-design.md
- docs/content/components/button.mdx
- docs/content/components/card.mdx
- docs/src/components/Layout.tsx
context: https://www.figma.com/file/TIRxkIDpdqb52J52PldLxl/Guidelines?node-id=0%3A1
> feat(docs): update button + card

- .changeset/config.json
See https://github.com/changesets/changesets/pull/690 for more infos
> chore: use fixed versioning for system and components package

- .changeset/witty-months-smell.md
- packages/components/src/Label/Label.tsx
- packages/components/src/Select/Select.tsx
> refa(comp): fill prop instead of css or __baseCSS

- .changeset/afraid-ants-behave.md
- docs/src/components/Link.tsx
- docs/src/mdx.tsx
> chore: check docs link external or internal

- .changeset/sweet-kangaroos-retire.md
- docs/src/components/Navigation/Navigation.tsx
> 1739 add links to docs

- docs/templates/component.mdx
> docs: template for component docs

- packages/components/src/Field-Next/HelperText.stories.tsx
- packages/components/src/Field-Next/HelperText.test.tsx
- packages/components/src/Field-Next/HelperText.tsx
> feat: Intorduce <HelperText> for fields

- .changeset/ten-waves-approve.md
- docs/content/components/container.mdx
- packages/components/src/Container/Container.test.tsx
- packages/components/src/Container/Container.tsx
> feat(comp): Container with grid

- .changeset/ten-waves-approve.md
- docs/content/components/container.mdx
- packages/components/src/Container/Container.stories.tsx
- packages/components/src/Container/Container.test.tsx
- packages/components/src/Container/Container.tsx
> feat(comp): improve Container component

- packages/components/src/Field-Next/Field.test.tsx
- packages/components/src/Field-Next/HelpText.test.tsx
> fix: coverage to one hundred percent

- .changeset/proud-drinks-marry.md
- docs/content/components/breakout.mdx
- packages/components/src/Breakout/Breakout.stories.tsx
- packages/components/src/Breakout/Breakout.test.tsx
- packages/components/src/Breakout/Breakout.tsx
- packages/components/src/Breakout/index.ts
- packages/components/src/index.ts
> feat(comp): Introduce Breakout component

- .changeset/tiny-insects-perform.md
- docs/content/components/center.mdx
- packages/components/src/Center/Center.stories.tsx
- packages/components/src/Center/Center.test.tsx
- packages/components/src/Center/Center.tsx
- packages/components/src/Center/index.ts
- packages/components/src/index.ts
> feat(comp): Center component

- docs/src/components/DoAndDont.tsx
- docs/src/theme/components.ts
> refa(docs): refactor Do and Dont component

- .changeset/dirty-ads-prove.md
- docs/content/components/action-group.mdx
- docs/content/components/aside.mdx
- docs/content/components/aspect.mdx
- docs/content/components/badge.mdx
- docs/content/components/box.mdx
- docs/content/components/breakout.mdx
- docs/content/components/button.mdx
- docs/content/components/card.mdx
- docs/content/components/center.mdx
- docs/content/components/checkbox.mdx
- docs/content/components/columns.mdx
- docs/content/components/container.mdx
> refa(docs): update mdx pages with name a-c

- packages/system/src/hooks/index.ts
> fix: export useStateHook from system

- .changeset/slow-meals-drop.md
- docs/content/components/text-area.mdx
- packages/components/src/Field/FieldBase.test.tsx
- packages/components/src/Field/FieldBase.tsx
- packages/components/src/Field/HelpText.tsx
- packages/components/src/TextArea/TextArea.test.tsx
- packages/components/src/TextArea/TextArea.tsx
- packages/components/src/TextField/TextField.test.tsx
- packages/components/src/TextField/TextField.tsx
> fix: <TextField>/<TextArea> support variant/size

- docs/src/theme/component.ts
- docs/src/theme/components/Divider.style.ts
- docs/src/theme/components/index.ts
> fix: add forgotten Divider new styling to docs theme

- .changeset/odd-pens-flash.md
- packages/system/src/components/Box/utils.test.ts
- packages/system/src/components/Box/utils.ts
> feat: Add shorthands for group selectors

- .changeset/seven-toes-bake.md
- docs/content/components/inline.mdx
- packages/components/src/Inline/Inline.stories.tsx
- packages/components/src/Inline/Inline.tsx
> feat: <Inline> can align on x and y axis

- .changeset/slimy-coins-raise.md
- docs/src/components/CopyButton.tsx
- docs/src/components/CopySVGIcon.tsx
- docs/src/components/DoAndDont.tsx
- docs/src/components/Layout.tsx
- docs/src/components/Link.tsx
- docs/src/components/MarigoldTheme.tsx
- docs/src/components/Navigation/Navigation.tsx
- docs/src/components/Preview.tsx
- docs/src/components/ShowHideButton.tsx
- docs/src/components/ThemeSwitch.tsx
- docs/src/mdx.tsx
- packages/components/src/Breakout/Breakout.tsx
- packages/components/src/Center/Center.tsx
- packages/components/src/Container/Container.tsx
- packages/components/src/Tiles/Tiles.tsx
- packages/system/src/hooks/useComponentStyles.test.tsx
- packages/system/src/hooks/useResponsiveValue.test.tsx
- packages/system/src/hooks/useTheme.test.tsx
- packages/types/src/example.tsx
-> to make code base compatible with React 18 typings
> feat: Remove all occurances of `React.FC`

- .changeset/chilly-suits-explain.md
- docs/content/components/split.mdx
- packages/components/src/Split/Split.stories.tsx
- packages/components/src/Split/Split.test.tsx
- packages/components/src/Split/Split.tsx
- packages/components/src/Split/index.ts
- packages/components/src/index.ts
> feat: Introduce `<Split>`

- .changeset/late-glasses-lay.md
- docs/content/components/table.mdx
- packages/components/src/Table/Table.stories.tsx
- packages/components/src/Table/Table.test.tsx
- packages/components/src/Table/TableColumnHeader.tsx
> feat: Show sorting in `<Table>`

- .github/workflows/release.yml
> chore: Add release action

- .changeset/short-wombats-relate.md
- packages/components/src/Checkbox/Checkbox.test.tsx
- packages/components/src/Checkbox/Checkbox.tsx
> feat: forward ref for `<Checkbox>`

- .changeset/afraid-kids-stare.md
- packages/components/src/TextField/TextField.test.tsx
- packages/components/src/TextField/TextField.tsx
> feat: forward ref for `<FieldText>`

- .changeset/odd-pens-exist.md
- packages/components/src/TextArea/TextArea.stories.tsx
- packages/components/src/TextArea/TextArea.test.tsx
- packages/components/src/TextArea/TextArea.tsx
> feat: forward ref for `<TextArea>`

- .changeset/mean-moose-grab.md
- packages/components/src/Radio/Radio.test.tsx
- packages/components/src/Radio/Radio.tsx
> feat: forward ref for `<Radio>`

- .changeset/proud-dogs-attend.md
- packages/components/src/Select/Select.test.tsx
- packages/components/src/Select/Select.tsx
> feat: forward ref for `<Select>`

- .changeset/big-books-allow.md
- packages/components/src/Slider/Slider.test.tsx
- packages/components/src/Slider/Slider.tsx
> feat: forward ref for `<Slider>`

- .changeset/soft-donuts-fix.md
- config/storybook/main.ts
- config/storybook/package.json
- config/storybook/preview.tsx
- pnpm-lock.yaml
- themes/theme-b2b/src/index.ts
- Switched to a stacked layout that shows stories with all available themes
- Improved them switching
> feat: Stacked layout in Storybook for Chromatic

- .changeset/cool-mayflies-cheer.md
- docs-next/next.config.mjs
- docs-next/package.json
- docs-next/src/components/Link.tsx
- docs-next/src/components/Navigation/Navigation.tsx
- docs-next/src/config.ts
- docs-next/src/mdx.tsx
- docs-next/src/navigation.utils.ts
- docs-next/src/pages/404.tsx
- docs-next/src/theme/components/Link.style.ts
- packages/components/src/Link/Link.tsx
- pnpm-lock.yaml
refactored the link component for nextjs and add some styles
> docs: next link component

- docs-next/content/components/list.mdx
- packages/components/src/List/Context.ts
- packages/components/src/List/List.stories.tsx
- packages/components/src/List/List.test.tsx
- packages/components/src/List/List.tsx
- packages/components/src/List/ListItem.tsx
- packages/components/src/List/index.ts
- packages/components/src/theme.ts
- themes/theme-b2b/src/components/List.style.ts
> feat: new component list

- .changeset/chilly-needles-move.md
- packages/components/src/Button/Button.stories.tsx
- packages/components/src/Button/Button.test.tsx
- packages/components/src/Button/Button.tsx
> fix: justify content in `<Button>`

- .changeset/lazy-countries-act.md
- docs/content/foundation/icons.mdx
- packages/icons/src/action/Logout.tsx
- packages/icons/src/action/index.ts
> feat: new icon for logout

- .changeset/good-tomatoes-pull.md
- packages/components/src/Link/Link.stories.tsx
- packages/components/src/Link/Link.tsx
> fix: fix the links

- .changeset/tough-books-wonder.md
- docs/src/demos/index.ts
- docs/src/demos/theming-extend.demo.tsx
- docs/src/pages/introduction/theming.mdx
- packages/components/package.json
- packages/components/src/theme.test.tsx
- packages/components/src/theme.ts
- pnpm-lock.yaml
> feat: introduce `extendTheme` helper

- .changeset/cuddly-cherries-rush.md
- themes/theme-b2b/src/components/Table.style.ts
> refa: change table hover to `gray20`

- .changeset/shiny-camels-happen.md
- themes/theme-b2b/src/components/Select.style.ts
> refa: Change focus color to orange60

- .changeset/nervous-terms-vanish.md
- themes/theme-b2b/src/components/Button.style.ts
> feat: darken text and ghost butotn hover

- .changeset/famous-fireants-notice.md
- packages/icons/src/action/Logout.tsx
> feat: better `Logout` icon

- .changeset/three-cherries-sing.md
- themes/theme-b2b/src/components/Checkbox.style.ts
- themes/theme-b2b/src/components/Input.style.ts
- themes/theme-b2b/src/components/NumberField.style.ts
- themes/theme-b2b/src/components/Radio.style.ts
- themes/theme-b2b/src/components/Slider.style.ts
- themes/theme-b2b/src/components/Switch.style.ts
- themes/theme-b2b/src/components/TextArea.style.ts
> refa: change all focus colors to orange

- docs/src/pages/components/select.mdx
- docs/src/pages/components/table.mdx
- packages/components/src/Label/Label.tsx
- packages/system/src/components/Box/selector.ts
- themes/theme-core/src/components/Button.style.ts
- themes/theme-core/src/components/Dialog.style.ts
- themes/theme-core/src/components/Input.style.ts
- themes/theme-core/src/components/Label.style.ts
- themes/theme-core/src/components/Link.style.ts
- themes/theme-core/src/components/ListBox.style.ts
- themes/theme-core/src/components/Menu.style.ts
- themes/theme-core/src/components/Message.style.ts
- themes/theme-core/src/components/Radio.style.ts
- themes/theme-core/src/components/Table.style.ts
- themes/theme-core/src/components/index.ts
- themes/theme-core/src/index.ts
- also added required property to label for styling reasons.
> chore: improve core theme 

- .changeset/bright-moons-study.md
- packages/components/src/Card/Card.stories.tsx
- themes/theme-core/src/components/Card.style.ts
- themes/theme-core/src/components/Link.style.ts
- themes/theme-core/src/components/Text.style.ts
- themes/theme-core/src/components/index.ts
- in storybook is also a new example
> chore: add card, text style for core

- .github/ISSUE_TEMPLATE/2.bug.md
- add a link to a repl.it that can be forked to create reproducable buggy examples
closes #2572
> chore: update bug template with repl.it template

- .changeset/quiet-countries-reflect.md
- packages/components/src/Switch/Switch.tsx
> fix: set `<Switch>` width in flex so it doesn't shrink below a certain threshold

- packages/components/src/Table/Table.test.tsx
> chore: add table cell test

- packages/components/src/Columns/Columns.test.tsx
- packages/components/src/Columns/Columns.tsx
> chore: add columns test

- packages/components/src/Overlay/overlay.test.tsx
> chore: added overlay,popover, underlay tests

- .changeset/empty-cherries-lick.md
- packages/components/src/Message/Message.stories.tsx
- packages/components/src/Message/Message.tsx
- themes/theme-b2b/src/components/Message.style.ts
> feat: Improve `<Message>` look

- .changeset/twelve-timers-fly.md
- packages/system/src/components/SVG/SVG.tsx
> fix: icon size in button

- .changeset/cool-knives-rhyme.md
- themes/theme-b2b/src/components/ListBox.style.ts
- themes/theme-b2b/src/components/Menu.style.ts
- themes/theme-core/src/components/ListBox.style.ts
- themes/theme-core/src/components/Menu.style.ts
- themes/theme-unicorn/src/components/ListBox.style.ts
- themes/theme-unicorn/src/components/Menu.style.ts
> fix: set height to 25vh and overflow to auto for select box and menu

- docs/next.config.mjs
- docs/src/demos/components/Table/core-table-print.demo.tsx
- docs/src/demos/components/Table/index.ts
- docs/src/pages/recipes/table-recipes.mdx
- themes/theme-core/src/components/Table.style.ts
> docs: print table example

- .changeset/odd-gorillas-drum.md
- packages/components/src/Select/Select.stories.tsx
- themes/theme-b2b/src/components/ListBox.style.ts
- themes/theme-core/src/components/ListBox.style.ts
- themes/theme-unicorn/src/components/ListBox.style.ts
> fix: set max-height to ul instead of div

- docs/src/demos/components/Menu/index.ts
- docs/src/demos/components/Menu/menu-kebab-icon.demo.tsx
- docs/src/pages/components/menu.mdx
- packages/components/src/Menu/Menu.stories.tsx
> Add icon for kebab menu in docu and fix typo in stories

- .github/codecov.yml
- .github/workflows/test.yml
> fix: fix flags for codecov

- .changeset/plenty-penguins-drum.md
- themes/theme-b2b/src/index.ts
> feat: add default color to body

- .changeset/purple-eggs-grow.md
- themes/theme-core/src/index.ts
added as value xxsmall because we're using this a lot. Hope it's ok
> chore: fontSize to 13px in core theme

- .vscode/extensions.json
I have replaced the old extension with the recommended one.
> Replace deprecated extension

- packages/components/src/Breakout/Breakout.test.tsx
- packages/components/src/Breakout/Breakout.tsx
In Breakout grid-colums where not applied I don't know why, but if I write them seperatly they work
> fix: breakout grid columns style

- docs/tailwind.config.ts
Co-authored-by: sarahgm <sarahgm@users.noreply.github.com>
Co-authored-by: Osama Abdul Latif  <OsamaAbdellateef@users.noreply.github.com>
> fix: correct path of content property in docs

- themes/theme-b2b/src/components/NumberField.styles.ts
> fix: numberfield hover

- packages/components/src/Badge/Badge.stories.tsx
this is just to have a branch where we can comment.
> [DST-29]DESIGN-REVIEW-b2b

- docs/app/_components/ThemeMenu.tsx
- docs/theme/components/Button.styles.ts
- docs/theme/components/Menu.styles.ts
- docs/theme/tokens.ts
> docs: adjust styling of menu

- .github/workflows/docs.yml
- .github/workflows/release.yml
Co-authored-by: sarahgm <sarahgm@users.noreply.github.com>
Co-authored-by: Osama Abdul Latif  <OsamaAbdellateef@users.noreply.github.com>
> chore: manually deploy docs

- docs/package.json
- packages/components/package.json
- packages/types/package.json
- pnpm-lock.yaml
for reasons newest version of types/react: 18.2.21 not working correctly
> fix: react types

- .changeset/giant-deers-divide.md
- packages/components/src/HelpText/HelpText.stories.tsx
- packages/components/src/HelpText/HelpText.test.tsx
- packages/components/src/HelpText/_HelpText.tsx
old comopnent is still there until we moved all fields
> refa: `<HelpText>` to RAC

- .gitignore
Ignore .idea from jetBrains IDEs. Also removed duplicate entries.
> chore: add jetbrains IDE folder to gitignore

- .changeset/smart-crews-tease.md
- packages/components/src/Input/_Input.tsx
- packages/components/src/SearchField/SearchField.tsx
- packages/components/src/Slider/Slider.tsx
- packages/components/src/TextArea/TextArea.tsx
This PR removes some unnecessary exports.
> chore: remove some unnecessary exports

- .changeset/fast-hats-wash.md
- packages/components/src/NumberField/NumberField.tsx
- packages/components/src/SearchField/SearchField.tsx
- packages/components/src/TextField/TextField.tsx
TS throwed an error when placeholder is used in components which using the Input component.
> chore: add placeholder to Input components

- docs/content/components/content/badge/badge-dark.demo.tsx
https://reservix.atlassian.net/jira/servicedesk/projects/DSTSUP/queues/custom/609/DSTSUP-6
> FixDocs [DSTSUP-6]: Update Badge-Demo 

- docs/app/_components/SiteNavigation.tsx
- docs/app/_components/ThemeMenu.tsx
- docs/theme/components/Button.styles.ts
> docs: align navigations with content

- docs/theme/components/Dialog.styles.ts
(tw classes don't exist anymore)
> docs: fix mobile nav

- .changeset/large-masks-grin.md
- docs/ui/Token.tsx
- packages/system/src/style-props.tsx
Added some half space tokens that also exists in [tailwind](https://tailwindcss.com/docs/padding).
> chore: added half space tokens

- .changeset/sharp-dolls-fry.md
- pnpm-lock.yaml
- themes/theme-core/package.json
- themes/theme-core/tailwind.config.ts
caused by supporttickets: DSTSUP-58 and partly DSTSUP-61
> [DSTSUP-58]chore: Add scoped preflight plugin to normalize the core

- .changeset/empty-tips-perform.md
- pnpm-lock.yaml
- themes/theme-core/package.json
- themes/theme-core/tailwind.config.ts
this is know done inside the Reservix System (see core/main!21472)
> refa: remove css scoping

- .changeset/hip-coats-retire.md
- docs/ui/IconList.tsx
Icon has class hidden when it is copied from our Docs icons
> [DSTSUP-75]: Fixing icons in our docs to be copied correctly

- docs/content/components/form/textfield/textfield.mdx
- noted that this also was written in the description not only on props table
> docs: fix in description also html props

- config/eslint/package.json
- config/jest/package.json
- config/storybook/package.json
- docs/package.json
- package.json
- pnpm-lock.yaml
This reverts commit fede7560da8950e8d18d1778819e16661d289ece.
> Revert "chore(deps): update dependency typescript to v5.5.2 (#3960)"

- .changeset/three-zoos-wait.md
- themes/theme-b2b/src/components/Table.styles.ts
- noticed while writing table guidelines
> fix: fixed aligned column in table in b2b theme

- themes/theme-b2b/src/components/Table.styles.ts
updated the border because there was none so it was a bug
[ ] This change requires a UI-Kit update - inform Alex Tirado
- No, its correct in Figma
Table Header styles
> fix: add border to table header in b2b theme

- .github/workflows/test.yml
Updated codecov token in github settings and adjust it in the ci
devs
> fix: update codecov token and add to ci

- .changeset/silver-lies-tease.md
- docs/package.json
- docs/tailwind.config.ts
- packages/components/src/Overlay/Popover.tsx
- pnpm-lock.yaml
- themes/theme-b2b/src/components/Popover.styles.ts
- themes/theme-core/src/components/Popover.styles.ts
- themes/theme-docs/src/components/Popover.styles.ts
Offset of Popovers didn't work. Fixed now using the data attribute.
[ ] This change requires a UI-Kit update - inform Alex Tirado (@tirado-rx)
There should be some space between trigger and popover (Select, Menu, ...)
nope.
> fix([DST-500]): fix popover placement

- .changeset/itchy-berries-flash.md
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/Checkbox/CheckboxGroup.test.tsx
- packages/components/src/Checkbox/Context.tsx
Hopefully codecov does pick it up now. The error we currently have is basically a false positive. The branch is definetly tested ...
[ ] This change requires a UI-Kit update - inform Alex Tirado
Devs
> fix: Pass down appearance props and use context from CheckboxGroup to apply label width

- packages/components/src/Radio/Radio.test.tsx
Noticed while working on table guidelines there where coverage errors from radio group
> fix: add radio test for coverage reason

- .github/PULL_REQUEST_TEMPLATE.md
Now the template has a checkbox for the alex section :D
> chore: update PR template with checkbox

- .prettierignore
- config/prettier/index.js
- config/storybook/.storybook/main.ts
- docs/app/_components/SiteFooter.tsx
- docs/lib/mdx/rehype-component-demo.tsx
- docs/ui/Toc.tsx
- docs/ui/Token.tsx
- docs/ui/Typography.tsx
- package.json
- packages/components/src/Columns/Columns.stories.tsx
- packages/components/src/Overlay/Underlay.tsx
- packages/components/src/Switch/Switch.tsx
- packages/components/src/Table/TableSelectAllCell.tsx
- packages/types/src/index.ts
- packages/types/src/react.ts
- scripts/watch-tailwind.mjs
Seems like prettier didn't run on some files ... whoops.
> chore: fix and run prettier

- packages/components/src/Table/Table.tsx
removed some properties from table which we don't need
> remove some table props

- docs/ui/AppearanceDemo.tsx
Hopefully make the message better to understand :)
> docs: make disabled apperance selection message more direct

- docs/content/concepts/concepts-layouts.demo.tsx
Removed the card around the demo since it is no longer necessary.
> docs: make the layout demo prettier

- config/storybook/package.json
- pnpm-lock.yaml
Reverts marigold-ui/marigold#4097
> Revert "chore(deps): update storybook"

- docs/lib/utils.tsx
- docs/ui/TeaserCard.tsx
- themes/theme-docs/src/components/Card.styles.ts
> docs: cards in teaser list take full width and the cards will be of equal height

- docs/content/components/content/link/link.mdx
- docs/content/components/form/select/select.mdx
- docs/content/components/layout/inline/inline.mdx
> docs: add missing storybook hints

- docs/app/_components/CommandItems.tsx
please test if the command menu still works as it should be
> fix: fix command item types

- docs/content/components/form/button/button.mdx
- docs/content/components/form/select/select.mdx
Moved some related stuff to the alternative components.
> docs: add alternative components

- .changeset/new-rockets-talk.md
- packages/components/src/DatePicker/DatePicker.stories.tsx
Here the bugfix fromm our mob.
> Bugfix: fix datepicker storybook example

- packages/components/src/Dialog/Dialog.stories.tsx
- packages/components/src/Dialog/Dialog.test.tsx
- packages/components/src/Menu/Menu.test.tsx
- packages/components/src/Select/Select.test.tsx
Fixed some tests
- onClick warning still from accordion
> fix: adjust some tests

- .changeset/real-turtles-turn.md
- docs/content/develop/component-guidelines.mdx
I tried to write down the changes for the code guidelines regarding the usage of “default” values for styles.
> docs: update internal component guidelines

- .changeset/modern-keys-smell.md
- docs/app/_components/CommandItems.tsx
- docs/app/_components/SiteMenu.tsx
- docs/lib/config.ts
add internal page to command menu
> chore: add internal page to command menu

- docs/ui/ComponentDemo.tsx
> docs: allow to set a custom label width in demos

- .changeset/beige-snakes-develop.md
- packages/components/src/DatePicker/DatePicker.stories.tsx
- packages/components/src/DatePicker/DatePicker.test.tsx
- packages/components/src/DatePicker/DatePicker.tsx
- themes/theme-b2b/src/components/Calendar.styles.ts
- themes/theme-core/src/components/Calendar.styles.ts
- this was caused by a support ticket, changed isDateUnavailable to dateUnavailable, matching our code guidelines.
- added disabled styles for b2b and core theme
- added a test
- added a story
everything working?
> fix([DSTSUP-94]): Adjust date unavailable property and add styles for it on date picker

- docs/content/components/collection/table/table.mdx
- docs/content/components/collection/tag/tag.mdx
- docs/content/components/content/link/link.mdx
- docs/content/components/form/button/button.mdx
- docs/content/components/form/number-field/number-field.mdx
- docs/content/components/form/radio/radio.mdx
- docs/content/components/form/switch/switch.mdx
- docs/content/components/form/textfield/textfield.mdx
- docs/content/components/layout/inline/inline.mdx
- docs/content/components/layout/split/split.mdx
- docs/content/components/layout/stack/stack.mdx
- docs/content/components/overlay/menu/menu.mdx
- docs/content/components/overlay/tooltip/tooltip.mdx
removed  the badges which are 2 month and older and haven't got updates
> docs: update badges for pages < 2 month

- docs/app/releases/blog/[...slug]/layout.tsx
- docs/content/patterns/feedback-messages/confirmation-dialog.demo.tsx
- docs/content/releases/blog/release-2024-10-25.mdx
- docs/ui/mdx.tsx
- packages/components/src/Table/Table.stories.tsx
includes the new release blog 
@KadaStrophe
> docs: Release blog 25.10

- .changeset/tender-beds-relate.md
- docs/content/components/overlay/menu/menu-open-dialog.demo.tsx
fixed the demo in menu with dialog
> docs: adjust menu demo with dialog

- docs/app/_components/SiteMenu.tsx
- docs/app/_components/ThemeMenu.tsx
- docs/ui/ComponentDemo.tsx
- docs/ui/CopyButton.tsx
- docs/ui/StorybookHintMessage.tsx
Started tracking some custom events:
- when users copy code
- when users use the demo tabs
- when user change themes
- when users go to storybook from a component page
- when people use cmdk
> docs: track some events 🤫

- docs/app/page.tsx
- themes/theme-docs/src/components/Link.styles.ts
- hover styles for primary/seconday links
- slights wieder shiny button
> docs: update landing page styles

- themes/theme-docs/src/index.ts
- themes/theme-docs/src/preset.ts
- themes/theme-docs/src/screens.ts
Runtime and CSS (Tailwind) had different break points, this fixes that.
> docs: use correct screen sizes in theme

- .changeset/yellow-hotels-watch.md
- docs/content/components/layout/columns/collapse-columns.demo.tsx
- docs/content/components/layout/columns/columns.mdx
- docs/content/components/layout/columns/fit-width-columns.demo.tsx
- docs/content/components/layout/columns/layout-columns.demo.tsx
- docs/content/components/layout/columns/space-columns.demo.tsx
- docs/content/components/layout/columns/stretch-columns-switch.demo.tsx
- docs/content/components/layout/columns/stretch-columns.demo.tsx
- docs/content/components/layout/columns/table-layout-columns.demo.tsx
- packages/components/src/Columns/Columns.stories.tsx
Added more informations to the column documentation page. According to our template.
Is something missing?
> docs([DST-609]): Revise `<Columns>` documentation page

- docs/content/recipes/form-recipes/bookings-form.demo.tsx
- docs/content/recipes/form-recipes/organization-search.demo.tsx
I would not put a update badge and/or a changeset. Just a small thing.
> docs: improve code of form recipes examples a little bit

- .changeset/spotty-mails-accept.md
- docs/content/components/layout/aside/aside.demo.tsx
- docs/content/components/layout/aside/aside.mdx
- docs/content/components/layout/aside/rightside.demo.tsx
- docs/content/components/layout/aside/space.demo.tsx
- packages/components/src/Aside/Aside.stories.tsx
- packages/components/src/Aside/Aside.tsx
Revised `<Aside>` according to our new  component documentation template.
> docs([DST-614]): Revise `<Aside>` documentation

- docs/ui/PropsTable.tsx
> docs: adjust alignment of lists in props table

- .changeset/wild-peaches-know.md
- docs/content/components/layout/grid/grid-holy-grail.demo.tsx
- docs/content/components/layout/grid/grid.mdx
- packages/components/src/Grid/Grid.stories.tsx
- packages/components/src/Grid/GridArea.tsx
Updated the docs according to our new template.
> docs([DST-622]): Revise `<Grid>` documentation page

- .changeset/new-paws-carry.md
- packages/components/src/Calendar/Calendar.stories.tsx
- packages/components/src/DateField/DateField.stories.tsx
- packages/components/src/DatePicker/DatePicker.stories.tsx
- packages/components/src/Dialog/Dialog.stories.tsx
- packages/components/src/HelpText/HelpText.stories.tsx
- packages/components/src/SearchField/SearchField.stories.tsx
> bugfix([DST-627]): replace useState import from storybook

- docs/content/getting-started/overview.mdx
> bugfix([DST-631]): fix faq redirect

- packages/components/src/Menu/Menu.stories.tsx
Correct labels in menu stories
> hotfix([DST-632]): correct labels in menu stories

- docs/ui/blog/LatestPost.tsx
- docs/ui/blog/PostList.tsx
MDX not compiled in overview pages for releases
MDX working as expected? 
> fix([DST-635]): fix MDX in Release Overview pages for descriptions

- packages/components/src/TagGroup/TagGroup.stories.tsx
> fix([DST-636]): fix tag story

- config/eslint/package.json
- config/jest/package.json
- config/storybook/package.json
- docs/app/_components/CommandItems.tsx
- docs/package.json
- docs/ui/IconList.tsx
- docs/ui/TeaserCard.tsx
- docs/ui/Toc.tsx
- package.json
- packages/components/package.json
- packages/components/src/Accordion/Accordion.tsx
- packages/components/src/Accordion/useAccordionItem.ts
- packages/components/src/Aside/Aside.tsx
- packages/components/src/DateField/DateField.tsx
- packages/components/src/DateField/DateInput.tsx
- packages/components/src/Input/Input.tsx
- packages/components/src/SearchField/SearchField.tsx
- packages/components/src/Table/Table.tsx
- packages/components/src/Table/TableCell.tsx
- packages/components/src/Table/TableSelectAllCell.tsx
- packages/components/src/test.utils.tsx
- packages/icons/package.json
- packages/system/package.json
- packages/types/package.json
- packages/types/src/react.ts
- pnpm-lock.yaml
> chore: update to react 19

- docs/app/_components/CommandItems.tsx
fixed an error you get when building docs.
> docs([DST-640]): fix build error

- docs/content/components/content/badge/badge.mdx
- docs/content/components/content/card/card.mdx
- docs/content/components/form/button/button.mdx
- docs/content/components/form/datefield/datefield.mdx
- docs/content/components/form/datepicker/datepicker.mdx
- docs/content/components/form/slider/slider.mdx
- docs/content/components/layout/aside/aside.mdx
- docs/content/components/layout/center/center.mdx
- docs/content/components/layout/columns/columns.mdx
- docs/content/components/layout/scrollable/scrollable.mdx
- docs/content/components/overlay/dialog/dialog.mdx
- docs/content/patterns/loading-states/loading-states.mdx
removed badges from docs older than a month
> docs([DST-639]): remove old badges

- .github/workflows/release.yml
> fix([DST-651]): adjust release action for slack notification

- .changeset/fresh-gifts-peel.md
- themes/theme-core/src/styles.css
- [] This change requires a UI-Kit update - inform Alex Tirado (@tirado-rx)
Examples:
> feat[DST-641]: add normalization from core tailwind v3

- .changeset/afraid-carrots-carry.md
- packages/components/src/Pagination/Pagination.stories.tsx
- packages/components/src/Pagination/Pagination.tsx
* results counter shows now the correct data ranges
* when changing the pagesize the first page will be selected
> bugfix[DSTSUP-100]: Bug in pagination component

- themes/theme-b2b/src/theme.css
- themes/theme-core/src/theme.css
- themes/theme-docs/src/theme.css
> HOTFIX: fix links to find plugins

- .changeset/dull-crews-wink.md
- packages/components/src/Table/Context.tsx
- packages/components/src/Table/Table.test.tsx
- packages/components/src/Table/Table.tsx
- packages/components/src/Table/TableBody.tsx
- packages/components/src/Table/TableHeaderRow.tsx
- packages/system/src/types/theme.ts
- themes/theme-b2b/src/components/Table.styles.ts
- themes/theme-core/src/components/Table.styles.ts
- themes/theme-docs/src/components/Table.styles.ts
Context: Need this to styles RUI tables
> feat([DST-689]): Allow to style body and header row of a `<Table>`

- docs/ui/ColorTable.tsx
> chore[DST-700]: refactoring color table

- packages/components/src/RouterProvider/RouterProvider.stories.tsx
- packages/components/src/Scrollable/Scrollable.stories.tsx
- packages/components/src/Table/TableColumn.stories.tsx
- packages/components/src/Tooltip/TooltipTrigger.stories.tsx
> fix([DST-709]): fix some stories again using `useState`

- .changeset/nasty-students-roll.md
- docs/content/getting-started/get-in-touch.mdx
Added other channels to our get in touch page
Links are working correctly
> chore([DST-711]): add more channels to Get in touch page

- packages/components/src/TagGroup/Tag.tsx
- packages/components/src/TagGroup/TagGroup.stories.tsx
- themes/theme-b2b/src/components/Tag.styles.ts
- themes/theme-core/src/components/Tag.styles.ts
The Tag component should have styles for disabled state , you can check this state into the MultiSelectTags story 
> Adding disabled styles for `<Tag>` component 

- packages/components/src/SelectList/SelectListItem.tsx
> fix: remove center from `<SelectList>`

- themes/theme-rui/src/components/Calendar.styles.ts
> fix: fix border in calendar

- .changeset/empty-wombats-design.md
- themes/theme-rui/package.json
- themes/theme-rui/src/theme.css
Now the mixins should be found.
> Fix mixins

- themes/theme-rui/package.json
> add missing exports for styles

- .changeset/spicy-pigs-beg.md
- themes/theme-rui/src/theme.css
> fix: Use stone value without rgba to keep oklch color

- .changeset/afraid-candles-add.md
- packages/components/src/Multiselect/Multiselect.tsx
- pnpm-lock.yaml
To keep backwards compatability we use UseId from react-aria utils like in the XLoader.
MultiSelect still works.
> [DST-769]: use useId from react-aria utils

- docs/package.json
- package.json
- pnpm-lock.yaml
> update types/node major version

- config/eslint/package.json
- config/prettier/package.json
- pnpm-lock.yaml
> update eslint and prettier major versions

- .changeset/large-donkeys-rule.md
- themes/theme-b2b/src/components/Input.styles.ts
- themes/theme-core/src/components/Input.styles.ts
> fix([DSTSUP-118]): Fix icon position in input fields

- .changeset/six-fans-hug.md
- themes/theme-rui/src/components/SectionMessage.styles.ts
> chore([DSTSUP-111]): Icon size in `<SectionMessage>`

- .changeset/afraid-steaks-hang.md
- packages/components/src/Autocomplete/Autocomplete.test.tsx
- packages/components/src/ComboBox/ComboBox.test.tsx
- packages/components/src/ListBox/ListBoxItem.tsx
- packages/components/src/Provider/OverlayContainerProvider.test.tsx
- packages/components/src/SearchField/SearchField.test.tsx
- packages/components/src/Select/Select.test.tsx
- packages/components/src/SelectList/SelectList.test.tsx
- packages/system/src/types/theme.ts
- themes/theme-b2b/src/components/ListBox.styles.ts
- themes/theme-core/src/components/ListBox.styles.ts
- themes/theme-docs/src/components/ListBox.styles.ts
- themes/theme-rui/src/components/ListBox.styles.ts
Rename `option` in styles file for `<ListBox>` in `item`
> refa([DST-720]): Rename `option` to `item` in styles for `<ListBox>`

- .changeset/beige-buses-smash.md
- packages/components/src/ComboBox/ComboBox.test.tsx
- packages/components/src/DateField/DateField.test.tsx
- packages/components/src/FieldBase/FieldBase.test.tsx
- packages/components/src/FieldBase/FieldGroup.test.tsx
- packages/components/src/Label/Label.stories.tsx
- packages/components/src/Label/Label.test.tsx
- packages/components/src/Label/Label.tsx
- packages/components/src/Switch/Switch.test.tsx
- packages/components/src/TextArea/TextArea.test.tsx
- pnpm-lock.yaml
- themes/theme-rui/src/components/Label.styles.ts
> style([DST-724]): Adjust required icon in RUI style

- docs/app/_components/SiteMenu.tsx
- packages/components/src/Dialog/Dialog.stories.tsx
keyboard dismissable in command menu; for some reasons dialogs dismissable is not working anymore with the command menu
keyboard dismissable?
> fix([DSTSUP-127]): Keyboard dismissable in command menu

- .husky/pre-commit
Got similiar deprecation message like here: https://github.com/typicode/husky/issues/1548
Updated husky setup accordingly.
> chore: fix husky

- .changeset/hot-socks-drum.md
> fix: rename package in changeset

- .changeset/rich-falcons-compete.md
- themes/theme-rui/src/components/Link.styles.ts
remove padding from link and removed unused variants 
> ([DST-862]): Update RUI link styles and remove empty variants

- .changeset/soft-hairs-rhyme.md
- packages/components/src/Calendar/Calendar.test.tsx
- packages/components/src/Calendar/Calendar.tsx
- packages/components/src/Calendar/CalendarListBox.tsx
- packages/components/src/Calendar/Context.tsx
- packages/components/src/Calendar/MonthListBox.tsx
- packages/components/src/Calendar/YearListBox.tsx
- packages/components/src/DatePicker/DatePicker.test.tsx
- packages/system/src/types/theme.ts
- themes/theme-b2b/src/components/Calendar.styles.ts
- themes/theme-core/src/components/Calendar.styles.ts
- themes/theme-rui/src/components/Calendar.styles.ts
Fix resizing of listboxes for month and year when calendar is open .
Calendar looks visually correct . 
Examples:
> refa([DST-715]): Refactor code from Calendar Component

- .changeset/eight-singers-kneel.md
- packages/components/src/Table/Table.stories.tsx
- themes/theme-rui/src/components/Table.styles.ts
> feat([DST-883]): new variant for RUI table

- .changeset/tiny-crews-prove.md
- docs/content/components/collection/table/table.mdx
- packages/components/src/Table/Table.stories.tsx
- packages/components/src/Table/Table.tsx
- packages/components/src/Table/TableCell.tsx
- packages/components/src/Table/TableCheckboxCell.tsx
- packages/components/src/Table/TableSelectAllCell.tsx
- themes/theme-rui/src/components/Table.styles.ts
In the Core we have often multi-lined table content. It is worth a try to add a property and guideline in docs to allow setting the alignment to top
alignment working
> feat([DST-884]): add vertical alignment property to table

- themes/theme-rui/src/components/Link.styles.ts
- themes/theme-rui/src/theme.css
> fix: add token for link

- .changeset/silent-garlics-battle.md
- packages/components/src/Overlay/Popover.tsx
- packages/components/src/Overlay/Underlay.tsx
- packages/components/src/Provider/OverlayContainerProvider.test.tsx
- packages/components/src/Tooltip/Tooltip.tsx
> fix[DST-812]: Migrate from UNSTABLE_portalContainer to UNSAFE_PortalProvider

- .github/workflows/component-tests.yml
s. https://vercel.com/docs/git/vercel-for-github#migrating-from-deployment_status
> [DST-806]: use repository-dispatch

- .changeset/silent-avocados-watch.md
- docs/content/components/content/icon/icon-fill.demo.tsx
- docs/content/components/content/icon/icon.mdx
Revise Icon page according to new component structure
> docs([DST-918]): Revise Icon page to match component pages

- .changeset/beige-cars-lie.md
- packages/components/src/Calendar/Calendar.stories.tsx
- packages/components/src/Calendar/Calendar.tsx
- themes/theme-rui/src/components/Calendar.styles.ts
Fix width property on calendar
width prpoerty working
> fix[DSTSUP-169]: Fix width property on Calendar component

- .changeset/tough-games-doubt.md
- packages/components/src/Button/Button.stories.tsx
- themes/theme-rui/src/components/Button.styles.ts
- themes/theme-rui/src/components/Link.styles.ts
- themes/theme-rui/src/utils.css
- also added a helper to ensure a11y on small things
> feat([DST-1005]): Add a "link" variant to `<Button>`

- .github/workflows/visual-regression-tests.yml
Created a new branch for triggering VRT and check for latest ui changes.
> chore: VRT apply latest diffs

- .changeset/chatty-eggs-drive.md
- docs/content/components/collection/tag/tag-remove-all.demo.tsx
- docs/content/components/collection/tag/tag.mdx
- packages/components/src/ComboBox/ComboBox.stories.tsx
- packages/components/src/TagGroup/TagGroup.stories.tsx
- packages/components/src/TagGroup/TagGroup.tsx
- packages/components/src/TagGroup/TagGroupRemoveAll.tsx
- packages/components/src/intl/messages.ts
- packages/system/src/types/theme.ts
- themes/theme-rui/src/components/Tag.styles.ts
Introduce a new feature that allows users to remove all tags at once. Update documentation and examples to reflect this new functionality.
> feat([DST-1008]): Introduce a "remove all" function for `<Tag.Group>`

- .changeset/all-beans-melt.md
- docs/app/_components/landingpage/AccessibiltySection.tsx
- docs/content/components/content/badge/badge-appearance.demo.tsx
- docs/content/components/content/card/card-appearance.demo.tsx
- docs/content/components/hooks-and-utils/extendTheme/button-variant.demo.tsx
- docs/content/components/layout/inset/inset-hv.demo.tsx
- docs/content/foundations/accessibility/accessibility-keyboard.demo.tsx
- docs/content/patterns/feedback-messages/confirmation-dialog.demo.tsx
- packages/components/src/Accordion/Accordion.tsx
- packages/components/src/Badge/Badge.tsx
- packages/components/src/Breadcrumbs/Breadcrumbs.tsx
- packages/components/src/Breadcrumbs/BreadcrumbsItem.tsx
- packages/components/src/Button/Button.tsx
- packages/components/src/Card/Card.stories.tsx
- packages/components/src/Card/Card.tsx
- packages/components/src/Collapsible/Collapsible.tsx
- packages/components/src/Collapsible/CollapsibleTrigger.tsx
- packages/components/src/Divider/Divider.tsx
- packages/components/src/Headline/Headline.tsx
- packages/components/src/IconButton/IconButton.tsx
- packages/components/src/Link/Link.tsx
- packages/components/src/Menu/Menu.tsx
- packages/components/src/Table/Table.tsx
- packages/components/src/Text/Text.tsx
- packages/components/src/Tooltip/Tooltip.tsx
- packages/components/src/XLoader/BaseLoader.tsx
-Make sure that every component variants and sizes are defined in the components types 
> feat([DST-1003]):  Update `variant` property to use defined types 

- .changeset/green-coats-search.md
- packages/components/src/List/List.stories.tsx
- themes/theme-rui/src/components/List.styles.ts
> feat([DST-1047]): Improve `<List>` styles and add `small` variant

- .changeset/sweet-fishes-lick.md
- themes/theme-rui/src/components/Badge.styles.ts
> fix([DST-1057]): Add missing background color for master and admin badge

- .changeset/pretty-chicken-hug.md
- themes/theme-rui/src/components/Accordion.styles.ts
> style([DST-1082]): Use correct accordion font-size
