marigold-ui/marigold

- README.md
- package.json
BREAKING CHANGE: Storybook files must  be of the format `*.stories.mdx`.
> chore(scripts): Make storybook the "default" development script

- config/storybook/main.js
- config/storybook/package.json
- config/storybook/preview.js
- packages/components/src/Label/Label.stories.mdx
- packages/components/src/Text/Text.stories.mdx
- themes/theme-unicorn/src/index.ts
- yarn.lock
- Use `storybook-addon-themes` to add a theme switch inside storybook
- Update `theme-unicorn` to be more fancy
- Remove all `<MarigoldProvider>` from stories, because it is added globally now!
Closes #154
> feat(storybook): allow to switch themes

- .dependabot/config.yml
We have the integration enabled anyway.
> chore: Remove `.dependabot`

- packages/components/src/Button/Button.stories.mdx
- packages/components/src/Button/Button.tsx
- themes/theme-b2b/src/index.ts
- rearranged theme order: added hover and disabled as pseudo classes to the variants `primary`, `secondary` and `ghost`
- added `disabled` as a property
- updated stories, properly filled in the property table
> feat: improve and cleanup <Button>

- config/jest/index.js
#192
This is why Icons are just using the SVG-component which is tested seperate
> chore: ignore icons in jest

- package.json
easier for debugging. now every time you start storybook, it opens with the same port number
> chore: set port for storybook

- packages/components/src/Select/Select.test.tsx
- packages/components/src/Select/Select.tsx
> refa: make <Select> use `useStyles` hook instead of <Box>

- packages/components/src/Alert/Alert.tsx
- packages/components/src/Badge/Badge.tsx
- packages/types/src/index.ts
Also HTMLProps have a different name now. Reason: https://react-typescript-cheatsheet.netlify.app/docs/advanced/patterns_by_usecase/#componentprops
Closes #794
> feat: Make `ComponentWithAs` and HTMLProps more awesome

- packages/components/src/Heading/Heading.stories.mdx
- packages/components/src/Heading/Heading.test.tsx
- packages/components/src/Heading/Heading.tsx
closes #802
We could also write that default as = variant. Then you only have to type one prop. 
I think users only pass variant and then you have different variant and as.
@sebald
> add as prop to Heading

- package.json
- yarn.lock
- @emotion/css was there by accident
- eslint-config-react-app was there because of a hoisting issue with yarn 1.x
> chore: cleanup package deps

- .changeset/spicy-months-behave.md
- jest.config.js
- packages/components/src/Box/Box.tsx
- packages/types/package.json
- packages/types/src/example.tsx
- packages/types/src/index.ts
- Use the common name, see https://react-typescript-cheatsheet.netlify.app/docs/advanced/patterns_by_usecase/#polymorphic-components-eg-with-as-props
- Add polymorphic type that doesn't have a ref
This is some groundwork for #1111
> feat(types): Clarify and improve as prop related types

- .changeset/wild-mirrors-speak.md
- packages/components/src/Select/Select.tsx
> feat(comp): remove useStyles from Select

- .changeset/young-badgers-dance.md
- docs/content/components/button.mdx
- docs/src/components/DoAndDont.tsx
- docs/src/theme/components.ts
closes #1496 
`<Box as="span" mr="xsmall">` will be removed if we with the Inline component. Will do this next.
> fix(docs): DoAndDont component

- .changeset/clean-cats-jog.md
- packages/components/src/Provider/GlobalStyles.tsx
- packages/components/src/Provider/MarigoldProvider.test.tsx
- packages/components/src/Provider/MarigoldProvider.tsx
- packages/components/src/Provider/index.ts
- packages/system/src/Global.test.tsx
- packages/system/src/Global.tsx
- packages/system/src/index.ts
- Remove emotion import form `components` so that it doesn't leak outside system package
> feat: add normalization for body and html & fix emotion leak

- .changeset/happy-peaches-arrive.md
- docs/content/components/button.mdx
- docs/content/components/inline.mdx
- packages/components/src/ActionGroup/ActionGroup.test.tsx
- packages/components/src/Button/Button.test.tsx
- packages/components/src/Button/Button.tsx
> feat(comp): remove span from button + add some styles incl. space prop to button

- .changeset/afraid-buses-travel.md
- docs/gatsby-node.js
- docs/src/pages/index.tsx
mdx pages are shown "Navigated to ${page}" at the end of every page. This comes from gatsby-node (line 15). Detected with GIT bisect 🎉
This is our current solution and will be replaced with a good landing page in the future.
> feat(docs): navigate to installation to fix bug

- docs/src/mdx.tsx
> fix: use gatsby link in mdx

- .changeset/plenty-tools-visit.md
- packages/components/src/Button/Button.test.tsx
- packages/icons/src/Icon.test.tsx
- packages/system/src/SVG.test.tsx
- packages/system/src/SVG.tsx
#1691 because in this issue i noticed that a svg should process the defined color values from a theme
> feat: extend svg fill prop to handle theme color

- packages/components/src/Field-Next/Label.stories.tsx
- packages/components/src/Field-Next/Label.test.tsx
- packages/components/src/Field-Next/Label.tsx
- no variants anymore
- no disabled (not possible anyway)
- improve a11y
Ref #1889
> feat: Refactor <Label>

- .changeset/cuddly-bikes-reflect.md
- docs/content/components/stack.mdx
- docs/src/pages/index.tsx
- packages/components/src/Stack/Stack.stories.tsx
- packages/components/src/Stack/Stack.test.tsx
- packages/components/src/Stack/Stack.tsx
- packages/components/src/Tiles/Tiles.stories.tsx
- packages/tokens/src/shadow.stories.tsx
- packages/tokens/src/typography.stories.tsx
> feat: <Stack> can align on x and y axis

- .changeset/wet-onions-love.md
- docs/content/components/table.mdx
- packages/components/src/Table/Table.stories.tsx
- packages/components/src/Table/Table.test.tsx
- packages/components/src/Table/Table.tsx
> feat: Add option to stretch `<Table>`

- .changeset/brave-meals-hammer.md
- packages/components/src/Switch/Switch.test.tsx
- packages/components/src/Switch/Switch.tsx
> feat: forward ref for `<Switch>`

- .changeset/real-days-crash.md
- docs-next/next.config.mjs
- docs-next/src/pages/_document.tsx
(we don't want to use i18n, since it produces /en/ URL when building)
> feat: fix lang settings in nextjs

- .changeset/tender-swans-fly.md
- packages/components/src/Button/Button.stories.tsx
- packages/components/src/Button/Button.test.tsx
- packages/components/src/Button/Button.tsx
- themes/theme-b2b/src/components/Button.style.ts
> feat: `<Button>` correctly pass through all native props and option to take full width

- .changeset/plenty-goats-rescue.md
- packages/components/src/Table/Context.tsx
- packages/components/src/Table/Table.stories.tsx
- packages/components/src/Table/Table.test.tsx
- packages/components/src/Table/Table.tsx
- packages/components/src/Table/TableCell.tsx
- packages/components/src/Table/TableColumnHeader.tsx
- packages/components/src/Table/TableRow.tsx
- themes/theme-b2b/src/components/Table.style.ts
- themes/theme-core/src/components/Table.style.ts
- themes/theme-unicorn/src/components/Table.style.ts
When a table has `selectionMode = "none"`(default) we can safely let users select text.
closes #2365
> feat: Make text in non-interactive tables selectable

- .changeset/young-readers-switch.md
- packages/components/src/Columns/Columns.stories.tsx
- packages/components/src/Columns/Columns.test.tsx
- packages/components/src/Columns/Columns.tsx
> fix: `Columns` work with complex and different children types

- docs/src/theme/root.ts
Why: because the demo codes are getting very long (Tiles, Tables)
> docs: set maxHeight for code demos

- .changeset/unlucky-papayas-tell.md
- docs/src/demos/components/Breakout/basic-breakout.demo.tsx
- docs/src/demos/components/Breakout/horizontal-breakout.demo.tsx
- docs/src/demos/components/Breakout/vertical-breakout.demo.tsx
- docs/src/pages/components/breakout.mdx
- packages/components/src/Breakout/Breakout.stories.tsx
- packages/components/src/Breakout/Breakout.test.tsx
- packages/components/src/Breakout/Breakout.tsx
Change horizontalAlign and verticalAlign to alignX and alignY for a better developer experience.
> chore: change property names in breakout to alignX and alignY

- .changeset/rare-bears-dance.md
- packages/components/src/NumberField/NumberField.tsx
- before this fix, browsers will not let the input shrink below a certain threshold (<200px)
> fix: allow `<NumberField>` with little width

- .changeset/wicked-clocks-smoke.md
- docs/src/components/IconList/IconList.tsx
- docs/src/demos/components/Tiles/index.ts
- docs/src/demos/components/Tiles/tiles-autoRows.demo.tsx
- docs/src/demos/components/Tiles/tiles-complex.demo.tsx
- docs/src/demos/components/Tiles/tiles-itemwidth.demo.tsx
- docs/src/demos/components/Tiles/tiles-spacing.demo.tsx
- docs/src/demos/components/Tiles/tiles-stretch.demo.tsx
- docs/src/demos/concepts-layouts.demo.tsx
- docs/src/pages/components/tiles.mdx
- packages/components/src/Card/Card.stories.tsx
- packages/components/src/Tiles/Tiles.stories.tsx
- packages/components/src/Tiles/Tiles.test.tsx
- packages/components/src/Tiles/Tiles.tsx
`<Tiles>` can now be used as a grid with fixed widths or fully respsonsive.
BREAKING CHANGE: Renamed the whole API. Please checkout the documentation at https://marigold-ui.io/components/tiles/#props
closes #2603
> feat: `<Tiles>` can switch between responsive and static modes

- docs/theme/components/Underlay.styles.ts
- docs/theme/tokens.ts
- themes/theme-b2b/src/components/Underlay.styles.ts
- previous color secondary was no token
- backdrop was missing
> fix: Underlay Color and Backdrop for Docs

- packages/components/src/FieldBase/FieldBase.tsx
- packages/components/src/FieldBase/_FieldBase.tsx
> fix: `FieldBase` renders empty element when no label is given

- packages/components/src/Button/Button.tsx
- packages/components/src/ComboBox/ComboBox.test.tsx
from our comment in code: // Button is currently only component accepting className because of internal use.
there was classNames allowed but forgot. to pass it on 👀
noticed by copy button in docs
> fix: fix button again

- .changeset/odd-cats-design.md
- packages/components/src/FieldBase/_FieldBase.tsx
For our form components we need the `data-required` attribute to switch the label to bold. To avoid using `useStateProps` the attribute `data-required` is set onto the component. This attribute depends on `isRequired`.
> chore: add data-required attribute for label

- .changeset/forty-numbers-sneeze.md
- docs/content/recipes/core-table-print.demo.tsx
In docs the core print example has two overlapping elements. Fixed them with layout components.
> chore: fix core print demo example

- themes/theme-b2b/src/components/NumberField.styles.ts
When focusing the number field, the edges of the input are rounded off. I remove this css to have a uniform appearance.
> chore[DST-238]: remove rounded borders from numberfield

- .changeset/tricky-poems-relax.md
- packages/components/src/Accordion/Accordion.stories.tsx
- packages/components/src/Accordion/AccordionItem.tsx
Two bugfixes concerning the accordion component:
- fix selectionMode='multiple' - the correct keys are now selected
- allow also numeric values for prop **defaultExpandedKeys** to match the definition (export type Key = string | number;)
> [DSTSUP-4] accordion item do not collapse and hide after first click

- .changeset/ninety-onions-give.md
- packages/components/src/Columns/Columns.tsx
does not to seem to have any effect.
> refa: remov cloning children in `<Columns>`

- .changeset/angry-elephants-wait.md
- docs/content/components/content/icon/icon.mdx
- docs/content/introduction/design-token-guidelines.mdx
There was a token change in https://github.com/marigold-ui/marigold/blob/82eb7fa03f35b75963d536c53cc68f6955a71383/themes/theme-core/src/tokens.ts#L283. So the docs are adjusted to it.
> [DST-264]: update token guidelines component height

- .changeset/dull-panthers-hang.md
- .github/workflows/release.yml
I adjust the release workflow according to https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions.
The last point shouldn't be necessary:
**If you are publishing a package for the first time you will also need to explicitly set access to public:
npm publish --provenance --access public**
> [DST-150]: adjust release workflow to  publish package with provenance

- .changeset/calm-gifts-love.md
- packages/components/src/ListBox/ListBox.tsx
[Kapture 2024-02-20 at 14.34.02.webm](https://github.com/marigold-ui/marigold/assets/985701/77b8a6a5-d64a-4e3a-8b28-da484d50a64a)
> fix([DSTSUP-31]): prevent immediately selection is Select/Combobox/Autocomplete

- .changeset/quick-books-peel.md
- themes/theme-b2b/tailwind.config.ts
- themes/theme-core/tailwind.config.ts
(this causes a lot of trouble when using them because it is **NOT** prefixed!)
> feat: remove normalization from themes when using CSS files

- .changeset/eighty-parents-burn.md
- themes/theme-core/src/root.ts
This is mostly so it doesn't mess up the styles by external CSS (e.g. our own docs)
> feat: add `line-height` (browser default) to the core theme

- .changeset/wicked-experts-provide.md
- packages/components/src/Columns/Columns.test.tsx
- packages/components/src/Columns/Columns.tsx
(also use positive comparison :D)
> fix: restore default `collapseAt` for `<Columns>`

- packages/components/package.json
(This caused our slack release message to not correctly link to the changelog)
> chore: add `directory` field to components package

- docs/ui/mdx.tsx
> docs: Show fullscreen view button only on larger examples

- docs/ui/Image.tsx
- docs/ui/mdx.tsx
Example:
```jsx
<Image
src="/familiar.svg"
width={500}
height={300}
alt="Man doubting, questioning, brainstorming"
caption="Image by vectorjuice on Freepik"
attribution="https://www.freepik.com/free-vector/self-management-life-coaching-man-doubting-questioning-brainstorming-identity-crisis-delirium-mental-confusion-confused-feelings-concept-pinkish-coral-bluevector-isolated-illustration_11664272.htm#query=think&position=1&from_view=author&uuid=5174f672-636e-482e-8976-6d54bd2b8180"
/>
```
Result:
> docs: images with captions

- .github/renovate.json
because to avoid long waits for updates
> chore: update renovate to weekly schedule

- docs/content/patterns/feedback-messages/confirmation-dialog.demo.tsx
Updated the dialog demo to remove a punctuation error and bring the content into conformity with the [Content Guidelines](https://www.marigold-ui.io/patterns/feedback-messages#content-guidelines) listed in the pattern.
> Orthography changes in Feedback Message demo

- docs/scripts/build-component-props.mjs
Make sure the `style` prop does not land in the documentation. This might happen sometimes because we extends from the RAC types.
[ ] This change requires a UI-Kit update - inform Alex Tirado
Can you find any `style` props in the tables? (e.g. Button had one)
Devs
> docs: remove `style` from pops table

- .changeset/lucky-plums-fix.md
- packages/components/src/Select/Select.test.tsx
- packages/components/src/Select/Select.tsx
Styles for the icons from theme wasn't applied in the `<Select>` component.
Cant really tests it I guess, because we don't yet apply styles to it. Noticed it because I wanted to add some styles in the docs theme.
Nope.
> fix: correctly apply styles to `<Select>` icon

- .changeset/two-wombats-work.md
- packages/components/src/Select/Select.tsx
- packages/components/src/TextField/TextField.tsx
In `Select` and `TextField` the appearance props (`variant` and `size`) where not passed to the `FieldBase` also.
-
Nope.
Marigold Devs
> fix: pass down appearance props to `FieldBase` in `Select` and `TextField`

- .changeset/sixty-bears-double.md
- packages/components/src/HelpText/HelpText.tsx
See DST-501.  Basically, because of `gap` there was some additional white space below the fields.
[ ] This change requires a UI-Kit update - inform Alex Tirado (@tirado-rx)
- Check if there is no whitespace, if no error and descritpion is given. 
- Still show error/description.
> fix([DST-501]): Don't render helptext if there is no error and description.

- docs/app/_components/SiteMenu.tsx
Whenever you switch between site you have to delete the latest search, this makes it easier.
[ ] This change requires a UI-Kit update - inform Alex Tirado (@tirado-rx)
1. cmd+k, search for something
2. go to a page
3. open cmdk again -> tada, text selected
nope
> docs: select text when site menu is opened

- docs/package.json
- docs/ui/PropsTable.tsx
- docs/ui/mdx.tsx
- pnpm-lock.yaml
We can no write markdown to describe props. yay! This is not perfect, but much better than randomly having markdown in our tables.
- [] This change requires a UI-Kit update - inform Alex Tirado (@tirado-rx)
Check out a PropsTable
No.
> docs: parse description in `PropsTable` as markdown

- .changeset/lucky-bugs-repair.md
- themes/theme-b2b/package.json
- themes/theme-b2b/src/tokens.ts
- themes/theme-b2b/tsup.config.ts
- themes/theme-core/package.json
- themes/theme-core/src/tokens.ts
- themes/theme-core/tsup.config.ts
- themes/theme-docs/package.json
- themes/theme-docs/src/tokens.ts
- themes/theme-docs/tsup.config.ts
A dedicated `@marigold/<theme-name>/tokens` export allows to only export the tokens without all the baggage of the others exports with should only be used to configure the MarigoldProvider and tailwind.
You can try it out when checking this out locally, I guess.
I want this for the OG image, I cannot have "client only" exports there which sadly come when you import the system or preset package.
> feat: add dedicated export for tokens to all themes

- .changeset/big-moons-pretend.md
- packages/components/src/Table/TableColumnHeader.tsx
Currently the sorting indicator is always shown on all columns in table. Now the sorting indicator is only shown when a column header is pressed and `allowsSorting` is set onto this.
> [DST-504]: Sorting indicator is always shown in table

- docs/ui/DosAndDonts.tsx
- themes/theme-docs/src/tokens.ts
If you have a page with lots of do/donts you dont see the actual  text anymore. This does hopfully improve the situation a bit.
Open the Table page. Compare to `main`.
> docs: make Dos and Donts less prominent

- docs/app/_components/SiteHeader.tsx
The link to the RAPP was not looking good on smaller screens. This fixes that.
> docs: make CTA button more clean on smaller screens

- .changeset/twelve-eyes-boil.md
- packages/components/src/SelectList/SelectList.tsx
- packages/components/src/SelectList/SelectListItem.tsx
I noticed that the selectlist layout breaks with the new select feature of having descriptions. So I tried to fix it
Test if the selectbox works as expected, it looks broken in main
> fix: fix SelectListItem layout

- .changeset/proud-radios-joke.md
- packages/components/src/Table/TableBody.tsx
- packages/components/src/test.utils.tsx
There was this error in tests `console.error
Warning: validateDOMNesting(...): <tr> cannot appear as a child of <table>. Add a <tbody>, <thead> or <tfoot> to your code to match the DOM tree generated by the browser.` I fix it with wrappig a `<tbody>` around the empty state
> fix: fix DOM tree for empty tables

- .changeset/spotty-tomatoes-cover.md
- themes/theme-core/src/components/ComboBox.styles.ts
- themes/theme-core/src/components/Input.styles.ts
- themes/theme-core/src/components/Select.styles.ts
- fixed `<Select>` disabled styles
- fixed `<Combobox>` icon styles
> fix[DSTSUP-86]: adjust select and combobox styles for core theme

- .changeset/mean-trees-begin.md
- packages/components/src/Autocomplete/Autocomplete.tsx
Fixed the overflowing popover width in autocomplete -> reason was the visibility of the clearing button
> fix: adjust visibility for autocomplete clear button

- docs/tailwind.config.ts
- themes/theme-b2b/tailwind.config.ts
- themes/theme-core/tailwind.config.ts
- themes/theme-docs/tailwind.config.ts
when building our themes and docs this warning appears: 
`warn - Your `content` configuration includes a pattern which looks like it’s accidentally matching all of `node_modules` and can cause serious performance issues.
warn - Pattern: `../packages/system/**/*.ts`
warn - See our documentation for recommendations:
warn - https://tailwindcss.com/docs/content-configuration#pattern-recommendations`
So I thought I follow the warning
everything working correctly?
> fix: remove node_modules from tailwind config

- .changeset/flat-bugs-sparkle.md
- packages/components/src/Menu/Menu.test.tsx
- packages/components/src/Menu/Menu.tsx
When using `<Menu>` with only a icon and no text element, there needs to be a `aria-label` on the button.
You can check this out in the docu, the theme switch menu!
> feat(Menu): pass `aria-label` to menu button instead of menu

- .changeset/bright-sloths-jog.md
- themes/theme-docs/src/components/Text.styles.ts
Removed the top margin because this lead to some weird extra whitespace.
Examples:
> style(docs): Improve whitespace of `p`

- .changeset/thick-masks-compete.md
- docs/content/components/form/checkbox/checkbox-appearance.demo.tsx
- docs/content/components/form/checkbox/checkbox-group.demo.tsx
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/Checkbox/CheckboxGroup.test.tsx
- Refactored the `CheckboxGroup` to be a compound component and align it with other components: `<CheckboxGroup>` -> `<Checkbox.Group>`
- Adjusted the Checkbox appearance demo a bit
Does it still work :D 
> feat: `CheckboxGroup` can now be used as a compound component

- .changeset/wet-parents-burn.md
- packages/components/src/Headline/Headline.tsx
- packages/components/src/Text/Text.tsx
- packages/types/src/html.ts
- packages/types/src/index.ts
Noticed that you can not use `Text` and `Headline` when you want to use ARIA labels ... which is important for accessibility. Fixed that by adding the relevant stuff to their props.
Not really something to test.
no
> feat(components): Make `<Text>` and `<Headline>` accessible by allowing ARIA labelling props

- .changeset/polite-plants-deliver.md
- packages/components/src/index.ts
- packages/components/src/types.ts
When working with a `<Table>` you can now use 
```ts
import type { Selection } from '@marigold/components';
```
instead of creating the type.
-
-
> feat(components): Expose `Selection` type for easy usage with `Table` and other components

- .changeset/yellow-lies-bake.md
- docs/app/_components/PortalContainer.tsx
- docs/ui/ComponentDemo.tsx
Because overlays inherited the root styles of the docs page instead of their theme, some stuff didn't display correctly.
Go to e.g. dialog page and open one. Should look more accurate.
> docs: Apply root styles to overlay portal so they are displayed correctly.

- themes/theme-docs/src/components/Badge.styles.ts
In latest vercel/docs the badge color is not set correctly. With this PR it will be fixed. Old token does not exist in code
> docs: fix the badge backgroundcolor

- .changeset/lovely-rivers-kiss.md
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/Table/TableRow.tsx
- themes/theme-core/src/components/Checkbox.styles.ts
- themes/theme-core/src/components/Table.styles.ts
Focus ring on the `<Checkbox>` was not there. Looked especially messed up when it was used in a table.
Does the checkbox have a focus ring when using the keyboard?!
> fix(components): Display `<Checkbox>` focus ring and adjust focus ring of `<Table>`

- .changeset/twelve-elephants-attack.md
- docs/content/components/form/combobox/combobox.mdx
This question came up in a conversaion with a product team dev. Important info that was missing!
> docs(Combobox): add info that section headers are not included wehen filtering

- docs/app/_components/SiteMenu.tsx
Noticed that they hotkey display is part of the a11y tree -> removed it.
> docs: remove `<Hotkey>` from a11y tree

- .changeset/purple-elephants-float.md
- packages/components/src/Table/Table.stories.tsx
The Controls are not working in the Nested Columns-Variant of the Table in Storybook. 
`args` was missing in certain stories.
Have a look at all table stories. Variants should work now.
@KadaStrophe
> bugfix([DSTSUP-92]): fix broken variants in table stories

- .changeset/mean-countries-own.md
- themes/theme-b2b/src/components/Label.styles.ts
Disabled color in labels was unreadable and had a really bad constrast (white background). Use regular text color instead.
Ref [DSTSUP-93]
[DSTSUP-93]: https://reservix.atlassian.net/browse/DSTSUP-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> style([DSTSUP-93]): Adjust disabled label color

- .changeset/eight-countries-sort.md
- packages/components/src/Dialog/Dialog.stories.tsx
- packages/components/src/Overlay/Modal.tsx
- themes/theme-b2b/src/components/Dialog.styles.ts
- themes/theme-core/src/components/Dialog.styles.ts
Using `size` with a dialog will allow the dialog to be at most sm/md/lg widths. Will be full size on smaller screens.
> style(dialog): make dialog sizes responsive

- .changeset/heavy-impalas-tie.md
- themes/theme-core/src/components/Underlay.styles.ts
Underlay was very bright and used a surface token for some reason.
> style(core): adjust the underlay color to be darker

- .changeset/rare-squids-shake.md
- packages/components/src/Text/Text.stories.tsx
- packages/components/src/Text/Text.test.tsx
- packages/components/src/Text/Text.tsx
Added possibility to not use the RAC text, needed for components like: Menu, Radio, Checkbox
Text with slots and without are working?
> chore: refa `<Text>` component

- .github/workflows/cleanup-branch-cache.yml
I've added a workflow to delete the github actions cache after merging a PR. Hopefully we avoid that our cached runs out of limit and we have no stucked actions anymore.
> chore: ([DST-597]): add cache delete workflow

- .changeset/dirty-flies-tan.md
- packages/components/src/Text/Text.test.tsx
- packages/components/src/Text/Text.tsx
Removes this warning:
```
Warning: React does not recognize the `elementType` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `elementtype` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
> fix(Text): Only apply `elementType` when RAC Text component is used.

- .changeset/popular-files-destroy.md
- config/storybook/.storybook/main.ts
- config/storybook/.storybook/preview.tsx
- config/storybook/package.json
- pnpm-lock.yaml
I added a11y addon to storybook s. https://storybook.js.org/addons/@storybook/addon-a11y
The dependency was already there but the panel wasn't active.
Open a component in storybook and check out the accesibility tab.
> docs: Added/activated a11y addon to storybook

- docs/content/components/form/button/button-press.demo.tsx
- docs/content/releases/blog/release-2024-10-25.mdx
> docs: fixed some typos

- .changeset/sweet-squids-design.md
- docs/ui/mdx.tsx
- themes/theme-docs/src/components/SectionMessage.styles.ts
Adjusted the text size of `code` blocks inside a `SectionMessage` so they are not bigger than the regular text in side the messages.
> docs: make `code` in `<SectionMessage>` look nicer

- themes/theme-docs/src/components/Card.styles.ts
The storybook hint looked slightly off because it used different colors than the props table. Not anymore!
> docs: Adjust the storybook hin to look like the props table

- .changeset/blue-scissors-admire.md
- packages/components/src/Select/Select.tsx
`isOpen` was set by default on the `<Select>` component. Seems to be somebody forgot to remove it when debugging something?
Is the select still working!?
> fix: Remove `isOpen` from `<Select>`

- docs/ui/AppearanceDemo.tsx
- themes/theme-b2b/src/components/Button.styles.ts
- themes/theme-core/src/components/Button.styles.ts
- automatically select first variant
- better display that there is no variant/size selected (indication by a "-")
This might fail with components that have a "default" (no variant/size) and additional variants, I would rather add a empty "default" to them to "fix" this then. If you find some, let me know!
**Before**
**After**
> docs: improve displaying the variant/size in the appearance demo

- .changeset/slow-turkeys-lay.md
<Text> was written without `` tags so the mdx complier can’t resolve it.
> chore([DST-625]):  update changeset to prevent build from failing

- .changeset/purple-seas-thank.md
- themes/theme-b2b/package.json
- themes/theme-core/package.json
- themes/theme-docs/package.json
while building the themes, there appears always: `The condition "types" here will never be used as it comes after both "import" and "require" [package.js]`
Fixed through removing the types entry in `exports` should be covered through: 
`"types": "./dist/index.d.ts",`
> fix([DST-638]): update package.jsons to resolve warning

- .changeset/fuzzy-panthers-vanish.md
- packages/components/src/Checkbox/Checkbox.tsx
Safari needs dimensions for SVGs!
- Open Safari, check if you see the checkmark when a `Checkbox` is checked.
> fix(DSTSUP-102): Set dimensions of checkmark

- .changeset/rude-flies-live.md
- packages/theme-plugins/package.json
- pnpm-lock.yaml
- themes/theme-b2b/package.json
- themes/theme-b2b/src/theme.css
- themes/theme-core/package.json
- themes/theme-core/src/theme.css
- themes/theme-docs/package.json
- themes/theme-docs/src/theme.css
Marigold 11 doesn'T work cause of missing dep. Create a package.json in theme-plugins, added as dependency in the other themes, adjust paths to plugins.
> HOTFIX: add theme-plugins as dependency

- .changeset/twenty-baboons-clap.md
- packages/components/src/Menu/Menu.tsx
- packages/components/src/Overlay/Popover.test.tsx
- packages/components/src/Overlay/Popover.tsx
- packages/components/src/Overlay/Underlay.tsx
Underlay stayed remaining open on mobile, while Popover was closed, 
also Popover styles for mobile were missing, added them back.
Components that open on small screen with a tray like `<Select>`, `<DatePicker>` and `<Menu>` components
> fix([DSTSUP-104]): mobile behaviour for popover

- docs/scripts/build-component-props.mjs
- packages/components/src/Button/Button.stories.tsx
- packages/components/src/Button/Button.test.tsx
- packages/components/src/ProgressCycle/ProgressCycle.test.tsx
- packages/components/src/ProgressCycle/ProgressCycle.tsx
- packages/components/src/Switch/Switch.test.tsx
- packages/system/src/types/theme.ts
- themes/theme-b2b/src/components/ProgressCycle.styles.ts
- themes/theme-b2b/src/components/index.ts
- themes/theme-core/src/components/ProgressCycle.styles.ts
- themes/theme-core/src/components/index.ts
- themes/theme-rui/src/components/Button.styles.ts
- themes/theme-rui/src/components/ProgressCycle.styles.ts
- themes/theme-rui/src/components/index.ts
- themes/theme-rui/src/theme.css
Button styles added in 4 variants according to OriginUI:
- primary
- secondary (default when no variant specified)
- destructive
- ghost
Also added states:
- disabled
- hover
- pending (for loading)
- focus-visible (with outline when tabbed into)
- [] This change requires a UI-Kit update - inform Alex Tirado (@tirado-rx , @benjirsvx )
Look into Storybook "Button".
The basic show all variants add once. Toggle disable to true.
Also look add loading story.
In general color should be checked.
For hover I used our accent color in secondary and ghost variant like OriginUI - I think this should be changed but idk which color to use.
> feat[DST-676]: add button styles to rui theme

- .changeset/chatty-clouds-jump.md
- packages/components/src/SelectList/SelectListItem.tsx
There were no space between the Checkbox and the children of SelectList when using multiple selection mode. 
> fix([DST-702]): add space for multiple selection mode in `<SelectList>`

- .changeset/late-crews-appear.md
- themes/theme-rui/src/theme.css
The alpha value causes syntax problems when using them in custom tokens. Instead we should use rgba for this use case.
> fix([DST-752]): use `rgba` instead of `alpha` value in our theme.css

- docs/content/components/form/search-field/search-field-basic.demo.tsx
- docs/content/components/form/search-field/searchfield-appearance.demo.tsx
- docs/content/components/form/slider/slider-form.demo.tsx
- packages/components/package.json
- packages/icons/package.json
- packages/system/package.json
The goal ist to use imports from marigold starting with _@marigold_ like we have it for the theme.
Instead of 
`
@source "../../../../../../../node_modules/@marigold/components";
@source "../../../../../../../node_modules/@marigold/system";
`
it should now be possible to use
`
@source "@marigold/components";
@source "@marigold/system";
`
Please check configuration.
> [DST-768]: add exports to marigold packages

- .changeset/fast-bees-count.md
- packages/components/src/HelpText/HelpText.tsx
> fix([DST-232]): Align icon in `<HelpText>` to the start

- themes/theme-rui/src/components/Pagination.styles.ts
The cursor did not change to a pointer cursor when hovering any element of the pagination component. This was attempted to be fixed with this PR.
[ ] does the cursor now change on hover?
Examples:
> ([DST-797]) added 'cursor-pointer' to pagination sub-components

- .changeset/tiny-feet-enjoy.md
- docs/content/components/form/checkbox/checkbox-appearance.demo.tsx
- docs/content/components/form/checkbox/checkbox-indeterminate.demo.tsx
- docs/content/components/form/switch/switch-appearance.demo.tsx
- packages/components/src/Checkbox/Checkbox.stories.tsx
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/Slider/Slider.tsx
- packages/components/src/Switch/Switch.stories.tsx
- packages/components/src/Switch/Switch.test.tsx
- packages/components/src/Switch/Switch.tsx
Added label prop to Switch and Checkbox,
deprecated the children prop as in `Slider` already exists
everything working as expected
> refa([DST-762]): Unify Label API Across Form Fields

- .changeset/kind-starfishes-remember.md
- packages/components/src/Overlay/Modal.tsx
Dialog was not dismissable when clicking on the left/right side, this was because of Modal classnames
> fix([DST-802]): remove unneeded classnames from `<Modal>`

- .changeset/forty-cheetahs-chew.md
- themes/theme-rui/src/components/Checkbox.styles.ts
- themes/theme-rui/src/components/Radio.styles.ts
Changed disabled styles of Checkbox and Radio. Now they match each other
Check if they look the same
> styles([DSTSUP-128]): Fix `disabled` styles for `Radio` and `Checkbox`

- .changeset/yellow-jobs-destroy.md
- themes/theme-rui/src/components/NumberField.styles.ts
In Core system `<NumberField>` styles for background was not correctly applied. Adding `bg-background` on the group and `bg-transparent` on the input part works fixing it
> styles([DST-823]): adjust RUI `<NumberField>` styles

- .changeset/breezy-roses-lick.md
- packages/components/src/Menu/ActionMenu.tsx
- packages/components/src/Menu/Menu.stories.tsx
- packages/components/src/Menu/Menu.test.tsx
- packages/components/src/Menu/Menu.tsx
- packages/system/src/types/theme.ts
- themes/theme-b2b/src/components/Button.styles.ts
- themes/theme-b2b/src/components/Menu.styles.ts
- themes/theme-core/src/components/Menu.styles.ts
- themes/theme-docs/src/components/Button.styles.ts
- themes/theme-docs/src/components/Menu.styles.ts
- themes/theme-rui/src/components/Menu.styles.ts
Menu does not match Origin UI standards, that because inside our Menu component we use a variant menu which does not exists on RUI Button. 
My proposal is to take the menu button styles out of the button and add it to the menu
everything working as expected and styles are the same as origin ui 
> chore([DST-853]): Refa styles for `<Menu>` button

- themes/theme-rui/src/components/Accordion.styles.ts
> fix([DST-867]): Prevent focus ring from being cut of in `Accordion`

- .changeset/quiet-buses-kick.md
- themes/theme-rui/src/components/Table.styles.ts
removed default right aligment
Examples:
> chore([DST-882]): Remove default right alignment in RUI table

- themes/theme-docs/src/components/CloseButton.styles.ts
- themes/theme-docs/src/components/index.ts
Close Button styles for docs were missing, so it crashed when mobile navigation was opened
> bugfix([DST-934]): fix mobile navigation

- .changeset/loud-badgers-wave.md
- packages/components/src/Accordion/Accordion.stories.tsx
- packages/components/src/Accordion/Accordion.test.tsx
- packages/components/src/Accordion/AccordionHeader.tsx
- themes/theme-rui/src/components/Accordion.styles.ts
Accordion.Header had messed up styles with `flex-1`. Moved it to the right place. So it works also again with Inline inside of it. See Story Core Example
> Fix([DSTSUP-181]): Adjust Accordion.Header styles to support full width

- .changeset/shiny-kangaroos-fry.md
- docs/content/components/form/checkbox/checkbox-description.demo.tsx
- docs/content/components/form/checkbox/checkbox.mdx
- packages/components/src/Checkbox/Checkbox.stories.tsx
- packages/components/src/Checkbox/Checkbox.test.tsx
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/SelectList/SelectList.test.tsx
- packages/components/src/Table/Table.test.tsx
- packages/system/src/types/theme.ts
- themes/theme-rui/src/components/Checkbox.styles.ts
- `<Checkbox>` now supports the `description` prop like other form fields.
Go to storybook (Checkbox -> With description) or to the checkbox documentation.
> feat([DST-1037]): Add `description` (help text) to `<Checkbox>` component

- .changeset/strong-seas-tease.md
- themes/theme-rui/src/components/Tag.styles.ts
- Adjusted border radius a bit to adhere origin ui
- reduce min height when empty state is small, e.g. only text
> fix(Tag): Adjust tag styles (no extra padding if empty state is small, e.g. only text)

- .changeset/wise-beans-exercise.md
- themes/theme-rui/src/components/HelpText.styles.ts
- themes/theme-rui/src/components/Select.styles.ts
-
Inspect the Select (Button) there should not be a margin anymore :D
> fix([DST-1046]): Remove extra padding at the bottom of `<Select>`.

- .changeset/four-vans-kick.md
- packages/components/src/Link/Link.stories.tsx
- themes/theme-rui/src/components/Link.styles.ts
add font size to link component
> fix([DST-1049]): Add 'text-sm' class to Link component styles

- .changeset/green-ties-applaud.md
- themes/theme-rui/src/components/Accordion.styles.ts
Add missing font color for accordion component
> fix([DST-1054]): Add missing font color in accordion component
